/* ============================================================
 *  func_index.h — UTILS 函数库 · 函数索引表（由 gen_functions.py 自动生成）
 * ============================================================ */

#ifndef FUNC_INDEX_H
#define FUNC_INDEX_H

typedef struct {
    const char *name;
    const char *section;
    const char *desc;
    const char *example;
} FuncInfo;

static const FuncInfo g_funcs[] = {
    {"print_int_array", "其他", "============================================================", "print_int_array(int arr[], int size)"},
    {"print_double_array", "其他", "其他", "print_double_array(double arr[], int size)"},
    {"fill_int_array", "其他", "其他", "fill_int_array(int arr[], int size, int value)"},
    {"fill_random_int", "其他", "其他", "fill_random_int(int arr[], int size)"},
    {"fill_random_range", "其他", "其他", "fill_random_range(int arr[], int size, int min, int max)"},
    {"reverse_int_array", "其他", "其他", "reverse_int_array(int arr[], int size)"},
    {"find_int", "其他", "其他", "find_int(int arr[], int size, int target)"},
    {"find_last_int", "其他", "其他", "find_last_int(int arr[], int size, int target)"},
    {"sum_int_array", "其他", "其他", "sum_int_array(int arr[], int size)"},
    {"avg_int_array", "其他", "其他", "avg_int_array(int arr[], int size)"},
    {"max_int_array", "其他", "其他", "max_int_array(int arr[], int size)"},
    {"min_int_array", "其他", "其他", "min_int_array(int arr[], int size)"},
    {"bubble_sort", "其他", "其他", "bubble_sort(int arr[], int size)"},
    {"insertion_sort", "其他", "其他", "insertion_sort(int arr[], int size)"},
    {"selection_sort", "其他", "其他", "selection_sort(int arr[], int size)"},
    {"max_subarray_sum", "其他", "求整型数组中连续子数组的最大和，返回最大和", "max_subarray_sum(int arr[], int size)"},
    {"binary_search", "其他", "其他", "binary_search(int arr[], int size, int target)"},
    {"merge_sorted_arrays", "其他", "其他", "merge_sorted_arrays(int arr1[], int size1, int arr2[], int size2, int *out_size)"},
    {"remove_at_index", "其他", "其他", "remove_at_index(int arr[], int *size, int index)"},
    {"insert_at_index", "其他", "其他", "insert_at_index(int arr[], int *size, int index, int value, int max_capacity)"},
    {"str_len", "其他", "============================================================", "str_len(const char *str)"},
    {"str_copy", "其他", "其他", "str_copy(char *dest, const char *src)"},
    {"str_cat", "其他", "其他", "str_cat(char *dest, const char *src)"},
    {"str_cmp", "其他", "其他", "str_cmp(const char *s1, const char *s2)"},
    {"str_find", "其他", "其他", "str_find(const char *haystack, const char *needle)"},
    {"count_char", "其他", "其他", "count_char(const char *str, char ch)"},
    {"remove_char", "其他", "其他", "remove_char(char *str, char ch)"},
    {"is_palindrome_str", "其他", "其他", "is_palindrome_str(const char *str)"},
    {"to_lower", "其他", "其他", "to_lower(char *str)"},
    {"to_upper", "其他", "其他", "to_upper(char *str)"},
    {"reverse_str", "其他", "其他", "reverse_str(char *str)"},
    {"str_to_int", "其他", "其他", "str_to_int(const char *str)"},
    {"int_to_str", "其他", "其他", "int_to_str(int num, char *buf)"},
    {"trim", "其他", "其他", "trim(char *str)"},
    {"count_words", "其他", "其他", "count_words(const char *str)"},
    {"factorial", "其他", "============================================================", "factorial(int n)"},
    {"is_prime", "其他", "其他", "is_prime(int n)"},
    {"gcd", "其他", "其他", "gcd(int a, int b)"},
    {"lcm", "其他", "其他", "lcm(int a, int b)"},
    {"power", "其他", "其他", "power(int base, int exp)"},
    {"is_perfect", "其他", "其他", "is_perfect(int n)"},
    {"fibonacci", "其他", "其他", "fibonacci(int n)"},
    {"rand_range", "其他", "其他", "rand_range(int min, int max)"},
    {"shuffle_array", "其他", "其他", "shuffle_array(int arr[], int size)"},
    {"read_file", "其他", "============================================================", "read_file(const char *filename)"},
    {"write_file", "其他", "其他", "write_file(const char *filename, const char *content)"},
    {"append_file", "其他", "其他", "append_file(const char *filename, const char *content)"},
    {"copy_file", "其他", "其他", "copy_file(const char *src, const char *dest)"},
    {"count_file_lines", "其他", "其他", "count_file_lines(const char *filename)"},
    {"safe_malloc", "其他", "============================================================", "safe_malloc(size_t size)"},
    {"safe_calloc", "其他", "其他", "safe_calloc(size_t count, size_t size)"},
    {"safe_realloc", "其他", "其他", "safe_realloc(void *ptr, size_t size)"},
    {"safe_free", "其他", "其他", "safe_free(void **ptr)"},
    {"copy_int_array", "其他", "其他", "copy_int_array(int src[], int size)"},
    {"copy_string", "其他", "其他", "copy_string(const char *src)"},
    {"debug_log", "其他", "============================================================", "debug_log(const char *format, ...)"},
    {"get_time_str", "其他", "其他", "get_time_str(char *buf)"},
    {"wait_for_key", "其他", "其他", "wait_for_key(void)"},
    {"clear_input_buffer", "其他", "其他", "clear_input_buffer(void)"},
    {"safe_fgets", "其他", "其他", "safe_fgets(char *buf, size_t size, FILE *stream)"},
    {"bit_set", "其他", "用于寄存器/端口位操作，命名已避开 HAL、标准外设库等固件库。", "bit_set(volatile uint8_t *reg, uint8_t bit)"},
    {"bit_clear", "其他", "清零：将寄存器第 bit 位清 0", "bit_clear(volatile uint8_t *reg, uint8_t bit)"},
    {"bit_toggle", "其他", "翻转：将寄存器第 bit 位取反", "bit_toggle(volatile uint8_t *reg, uint8_t bit)"},
    {"bit_is_set", "其他", "查询：返回 1 表示该位为 1，0 表示该位为 0", "bit_is_set(volatile uint8_t *reg, uint8_t bit)"},
    {"bit_is_clear", "其他", "查询：返回 1 表示该位为 0，0 表示该位为 1", "bit_is_clear(volatile uint8_t *reg, uint8_t bit)"},
    {"byte_get_high", "其他", "取 16 位数据的高字节", "byte_get_high(uint16_t val)"},
    {"byte_get_low", "其他", "取 16 位数据的低字节", "byte_get_low(uint16_t val)"},
    {"byte_combine", "其他", "由高字节 + 低字节组合成 16 位数据", "byte_combine(uint8_t hi, uint8_t lo)"},
    {"count_ones", "其他", "统计 32 位数据中 1 的个数（汉明重量）", "count_ones(uint32_t val)"},
    {"rotate_left", "其他", "32 位循环左移 n 位", "rotate_left(uint32_t val, uint8_t n)"},
    {"rotate_right", "其他", "32 位循环右移 n 位", "rotate_right(uint32_t val, uint8_t n)"},
    {"swap_bytes16", "其他", "16 位高低字节交换（大小端转换）", "swap_bytes16(uint16_t val)"},
    {"swap_bytes32", "其他", "32 位字节序反转（大小端转换）", "swap_bytes32(uint32_t val)"},
    {"is_little_endian", "其他", "判断当前平台是否小端字节序（1 小端，0 大端）", "is_little_endian(void)"},
    {"is_digit_char", "其他", "判断字符是否为数字 '0'~'9'", "is_digit_char(char c)"},
    {"is_alpha_char", "其他", "判断字符是否为字母 a~z / A~Z", "is_alpha_char(char c)"},
    {"is_alnum_char", "其他", "判断字符是否为数字或字母", "is_alnum_char(char c)"},
    {"is_space_char", "其他", "判断字符是否为空白符（空格/制表/换行等）", "is_space_char(char c)"},
    {"char_to_lower", "其他", "单个字符转小写", "char_to_lower(char c)"},
    {"char_to_upper", "其他", "单个字符转大写", "char_to_upper(char c)"},
    {"hex_char_to_int", "其他", "十六进制字符转数值（'0'-'9','a'-'f','A'-'F'），非法返回 -1", "hex_char_to_int(char c)"},
    {"int_to_hex_char", "其他", "数值(0~15)转十六进制字符，非法返回 '?'", "int_to_hex_char(int v)"},
    {"int_to_binary_str", "其他", "其他", "int_to_binary_str(int num, char *buf, int buf_size)"},
    {"int_to_octal_str", "其他", "十进制整数转八进制字符串", "int_to_octal_str(int num, char *buf)"},
    {"int_to_hex_str", "其他", "十进制整数转十六进制字符串（大写）", "int_to_hex_str(int num, char *buf)"},
    {"bin_str_to_int", "其他", "二进制字符串转十进制整数", "bin_str_to_int(const char *str)"},
    {"oct_str_to_int", "其他", "八进制字符串转十进制整数", "oct_str_to_int(const char *str)"},
    {"hex_str_to_int", "其他", "十六进制字符串转十进制整数", "hex_str_to_int(const char *str)"},
    {"count_digits", "其他", "统计十进制整数的位数（0 返回 1）", "count_digits(int n)"},
    {"reverse_int", "其他", "反转十进制整数（123 -> 321，-123 -> -321）", "reverse_int(int n)"},
    {"sum_digits", "其他", "求十进制整数各位数字之和", "sum_digits(int n)"},
    {"is_armstrong", "其他", "判断是否为水仙花数（阿姆斯特朗数）", "is_armstrong(int n)"},
    {"is_palindrome_num", "其他", "判断是否为回文数（121、1221 等）", "is_palindrome_num(int n)"},
    {"quick_sort", "其他", "快速排序（升序，原地）", "quick_sort(int arr[], int size)"},
    {"merge_sort", "其他", "归并排序（升序，原地，内部临时申请内存）", "merge_sort(int arr[], int size)"},
    {"heap_sort", "其他", "堆排序（升序，原地）", "heap_sort(int arr[], int size)"},
    {"rotate_array_left", "其他", "数组整体左旋 k 位（原地）", "rotate_array_left(int arr[], int size, int k)"},
    {"rotate_array_right", "其他", "数组整体右旋 k 位（原地）", "rotate_array_right(int arr[], int size, int k)"},
    {"remove_duplicates_int", "其他", "其他", "remove_duplicates_int(int arr[], int *size)"},
    {"str_substr", "其他", "============================================================", "str_substr(const char *str, int start, int len, char *buf, int buf_size)"},
    {"str_replace_char", "其他", "将字符串中所有 old_ch 替换为 new_ch，返回替换次数", "str_replace_char(char *str, char old_ch, char new_ch)"},
    {"str_starts_with", "其他", "判断字符串是否以 prefix 开头", "str_starts_with(const char *str, const char *prefix)"},
    {"str_ends_with", "其他", "判断字符串是否以 suffix 结尾", "str_ends_with(const char *str, const char *suffix)"},
    {"str_split", "其他", "其他", "str_split(const char *str, char delim, int *count)"},
    {"str_free_split", "其他", "释放 str_split 返回的字符串数组", "str_free_split(char **tokens, int count)"},
    {"list_create", "其他", "创建值为 data 的新节点（需 free 释放）", "list_create(int data)"},
    {"list_insert_head", "其他", "头插法：在链表头部插入节点", "list_insert_head(ListNode **head, int data)"},
    {"list_insert_tail", "其他", "尾插法：在链表尾部插入节点", "list_insert_tail(ListNode **head, int data)"},
    {"list_insert_sorted", "其他", "有序插入：按升序将节点插入有序链表", "list_insert_sorted(ListNode **head, int data)"},
    {"list_delete_value", "其他", "删除链表中所有等于 data 的节点", "list_delete_value(ListNode **head, int data)"},
    {"list_find", "其他", "查找第一个等于 data 的节点，返回节点指针（找不到返回 NULL）", "list_find(ListNode *head, int data)"},
    {"list_length", "其他", "获取链表长度", "list_length(ListNode *head)"},
    {"list_reverse", "其他", "反转链表（原地）", "list_reverse(ListNode **head)"},
    {"list_print", "其他", "打印链表：1 -> 2 -> 3 -> NULL", "list_print(ListNode *head)"},
    {"list_free", "其他", "释放整个链表并置 head 为 NULL", "list_free(ListNode **head)"},
    {"stack_create", "其他", "创建容量为 capacity 的栈", "stack_create(int capacity)"},
    {"stack_destroy", "其他", "销毁栈（释放内存）", "stack_destroy(Stack *s)"},
    {"stack_push", "其他", "入栈，0 成功，-1 失败（栈满）", "stack_push(Stack *s, int value)"},
    {"stack_pop", "其他", "出栈，0 成功，-1 失败（栈空）", "stack_pop(Stack *s, int *out)"},
    {"stack_peek", "其他", "查看栈顶元素（不出栈），0 成功，-1 失败", "stack_peek(Stack *s, int *out)"},
    {"stack_is_empty", "其他", "判断栈是否为空", "stack_is_empty(Stack *s)"},
    {"stack_is_full", "其他", "判断栈是否已满", "stack_is_full(Stack *s)"},
    {"stack_size", "其他", "获取栈中元素个数", "stack_size(Stack *s)"},
    {"queue_create", "其他", "创建容量为 capacity 的循环队列", "queue_create(int capacity)"},
    {"queue_destroy", "其他", "销毁队列（释放内存）", "queue_destroy(Queue *q)"},
    {"queue_enqueue", "其他", "入队，0 成功，-1 失败（队满）", "queue_enqueue(Queue *q, int value)"},
    {"queue_dequeue", "其他", "出队，0 成功，-1 失败（队空）", "queue_dequeue(Queue *q, int *out)"},
    {"queue_peek", "其他", "查看队首元素（不出队），0 成功，-1 失败", "queue_peek(Queue *q, int *out)"},
    {"queue_is_empty", "其他", "判断队列是否为空", "queue_is_empty(Queue *q)"},
    {"queue_is_full", "其他", "判断队列是否已满", "queue_is_full(Queue *q)"},
    {"queue_size", "其他", "获取队列中元素个数", "queue_size(Queue *q)"},
    {"xor_checksum", "其他", "异或校验和（数据逐字节异或）", "xor_checksum(const uint8_t *data, uint16_t len)"},
    {"checksum8", "其他", "8 位累加校验和（取累加和低 8 位）", "checksum8(const uint8_t *data, uint16_t len)"},
    {"checksum16", "其他", "16 位累加校验和（取累加和低 16 位）", "checksum16(const uint8_t *data, uint16_t len)"},
    {"crc8", "其他", "CRC-8 校验（多项式 0x07，初始值 0x00）", "crc8(const uint8_t *data, uint16_t len)"},
    {"crc16_modbus", "其他", "CRC-16 Modbus 校验（多项式 0xA001，初始值 0xFFFF）", "crc16_modbus(const uint8_t *data, uint16_t len)"},
    {"parity_check", "其他", "奇偶校验：返回 1 表示 1 的个数为奇数，0 为偶数", "parity_check(uint32_t val)"},
    {"bytes_to_hex_str", "其他", "其他", "bytes_to_hex_str(const uint8_t *data, uint16_t len, char *buf, uint16_t buf_size)"},
    {"hex_str_to_bytes", "其他", "其他", "hex_str_to_bytes(const char *hex, uint8_t *out, uint16_t max_len)"},
    {"soft_delay_ms", "其他", "软件延时约 ms 毫秒（需按主频微调循环次数）", "soft_delay_ms(uint32_t ms)"},
    {"soft_delay_us", "其他", "软件延时约 us 微秒（需按主频微调循环次数）", "soft_delay_us(uint32_t us)"},
    {"file_exists", "其他", "判断文件是否存在", "file_exists(const char *path)"},
    {"dir_exists", "其他", "判断目录是否存在", "dir_exists(const char *path)"},
    {"get_file_size", "其他", "获取文件大小（字节），失败返回 -1", "get_file_size(const char *path)"},
    {"create_dir", "其他", "创建目录，0 成功，-1 失败", "create_dir(const char *path)"},
    {"remove_dir", "其他", "删除空目录，0 成功，-1 失败", "remove_dir(const char *path)"},
    {"path_join", "其他", "其他", "path_join(const char *dir, const char *file, char *buf, int buf_size)"},
    {"get_file_ext", "其他", "获取文件扩展名（不含点，如 \"c\"），无扩展名返回空串", "get_file_ext(const char *path)"},
    {"get_base_name", "其他", "获取文件名（不含目录路径部分）", "get_base_name(const char *path, char *buf, int buf_size)"},
    {"run_cmd", "其他", "执行系统命令（返回命令返回值）", "run_cmd(const char *cmd)"},
    {"run_cmd_capture", "其他", "其他", "run_cmd_capture(const char *cmd)"},
    {"hex_dump", "其他", "其他", "hex_dump(const void *ptr, size_t len)"},
    {"UTILS_MIN", "常用宏", "宏定义", "UTILS_MIN(...)"},
    {"UTILS_MAX", "常用宏", "宏定义", "UTILS_MAX(...)"},
    {"UTILS_ABS", "常用宏", "宏定义", "UTILS_ABS(...)"},
    {"UTILS_ARRAY_SIZE", "常用宏", "宏定义", "UTILS_ARRAY_SIZE(...)"},
    {"UTILS_BIT", "常用宏", "宏定义", "UTILS_BIT(...)"},
    {"find_int_array", "其他", "查找元素下标", "find_int_array(int arr[], int size, int target)"},
    {"count_int_array", "其他", "统计元素出现次数", "count_int_array(int arr[], int size, int target)"},
    {"product_int_array", "其他", "数组元素乘积", "product_int_array(int arr[], int size)"},
    {"max_abs_int_array", "其他", "最大绝对值", "max_abs_int_array(int arr[], int size)"},
    {"min_abs_int_array", "其他", "最小绝对值", "min_abs_int_array(int arr[], int size)"},
    {"second_max_int_array", "其他", "第二大元素", "second_max_int_array(int arr[], int size)"},
    {"second_min_int_array", "其他", "第二小元素", "second_min_int_array(int arr[], int size)"},
    {"is_sorted_asc_int_array", "其他", "判断数组是否升序", "is_sorted_asc_int_array(int arr[], int size)"},
    {"is_sorted_desc_int_array", "其他", "判断数组是否降序", "is_sorted_desc_int_array(int arr[], int size)"},
    {"print_long_array", "其他", "打印数组元素", "print_long_array(long arr[], int size)"},
    {"sum_long_array", "其他", "数组元素求和", "sum_long_array(long arr[], int size)"},
    {"avg_long_array", "其他", "数组平均值", "avg_long_array(long arr[], int size)"},
    {"max_long_array", "其他", "数组最大值", "max_long_array(long arr[], int size)"},
    {"min_long_array", "其他", "数组最小值", "min_long_array(long arr[], int size)"},
    {"fill_long_array", "其他", "用指定值填充数组", "fill_long_array(long arr[], int size, long value)"},
    {"reverse_long_array", "其他", "反转数组", "reverse_long_array(long arr[], int size)"},
    {"find_long_array", "其他", "查找元素下标", "find_long_array(long arr[], int size, long target)"},
    {"count_long_array", "其他", "统计元素出现次数", "count_long_array(long arr[], int size, long target)"},
    {"product_long_array", "其他", "数组元素乘积", "product_long_array(long arr[], int size)"},
    {"copy_long_array", "其他", "复制数组(需free)", "copy_long_array(long arr[], int size)"},
    {"max_abs_long_array", "其他", "最大绝对值", "max_abs_long_array(long arr[], int size)"},
    {"min_abs_long_array", "其他", "最小绝对值", "min_abs_long_array(long arr[], int size)"},
    {"second_max_long_array", "其他", "第二大元素", "second_max_long_array(long arr[], int size)"},
    {"second_min_long_array", "其他", "第二小元素", "second_min_long_array(long arr[], int size)"},
    {"is_sorted_asc_long_array", "其他", "判断数组是否升序", "is_sorted_asc_long_array(long arr[], int size)"},
    {"is_sorted_desc_long_array", "其他", "判断数组是否降序", "is_sorted_desc_long_array(long arr[], int size)"},
    {"print_long_long_array", "其他", "打印数组元素", "print_long_long_array(long long arr[], int size)"},
    {"sum_long_long_array", "其他", "数组元素求和", "sum_long_long_array(long long arr[], int size)"},
    {"avg_long_long_array", "其他", "数组平均值", "avg_long_long_array(long long arr[], int size)"},
    {"max_long_long_array", "其他", "数组最大值", "max_long_long_array(long long arr[], int size)"},
    {"min_long_long_array", "其他", "数组最小值", "min_long_long_array(long long arr[], int size)"},
    {"fill_long_long_array", "其他", "用指定值填充数组", "fill_long_long_array(long long arr[], int size, long long value)"},
    {"reverse_long_long_array", "其他", "反转数组", "reverse_long_long_array(long long arr[], int size)"},
    {"find_long_long_array", "其他", "查找元素下标", "find_long_long_array(long long arr[], int size, long long target)"},
    {"count_long_long_array", "其他", "统计元素出现次数", "count_long_long_array(long long arr[], int size, long long target)"},
    {"product_long_long_array", "其他", "数组元素乘积", "product_long_long_array(long long arr[], int size)"},
    {"copy_long_long_array", "其他", "复制数组(需free)", "copy_long_long_array(long long arr[], int size)"},
    {"max_abs_long_long_array", "其他", "最大绝对值", "max_abs_long_long_array(long long arr[], int size)"},
    {"min_abs_long_long_array", "其他", "最小绝对值", "min_abs_long_long_array(long long arr[], int size)"},
    {"second_max_long_long_array", "其他", "第二大元素", "second_max_long_long_array(long long arr[], int size)"},
    {"second_min_long_long_array", "其他", "第二小元素", "second_min_long_long_array(long long arr[], int size)"},
    {"is_sorted_asc_long_long_array", "其他", "判断数组是否升序", "is_sorted_asc_long_long_array(long long arr[], int size)"},
    {"is_sorted_desc_long_long_array", "其他", "判断数组是否降序", "is_sorted_desc_long_long_array(long long arr[], int size)"},
    {"print_short_array", "其他", "打印数组元素", "print_short_array(short arr[], int size)"},
    {"sum_short_array", "其他", "数组元素求和", "sum_short_array(short arr[], int size)"},
    {"avg_short_array", "其他", "数组平均值", "avg_short_array(short arr[], int size)"},
    {"max_short_array", "其他", "数组最大值", "max_short_array(short arr[], int size)"},
    {"min_short_array", "其他", "数组最小值", "min_short_array(short arr[], int size)"},
    {"fill_short_array", "其他", "用指定值填充数组", "fill_short_array(short arr[], int size, short value)"},
    {"reverse_short_array", "其他", "反转数组", "reverse_short_array(short arr[], int size)"},
    {"find_short_array", "其他", "查找元素下标", "find_short_array(short arr[], int size, short target)"},
    {"count_short_array", "其他", "统计元素出现次数", "count_short_array(short arr[], int size, short target)"},
    {"product_short_array", "其他", "数组元素乘积", "product_short_array(short arr[], int size)"},
    {"copy_short_array", "其他", "复制数组(需free)", "copy_short_array(short arr[], int size)"},
    {"max_abs_short_array", "其他", "最大绝对值", "max_abs_short_array(short arr[], int size)"},
    {"min_abs_short_array", "其他", "最小绝对值", "min_abs_short_array(short arr[], int size)"},
    {"second_max_short_array", "其他", "第二大元素", "second_max_short_array(short arr[], int size)"},
    {"second_min_short_array", "其他", "第二小元素", "second_min_short_array(short arr[], int size)"},
    {"is_sorted_asc_short_array", "其他", "判断数组是否升序", "is_sorted_asc_short_array(short arr[], int size)"},
    {"is_sorted_desc_short_array", "其他", "判断数组是否降序", "is_sorted_desc_short_array(short arr[], int size)"},
    {"print_uint_array", "其他", "打印数组元素", "print_uint_array(unsigned int arr[], int size)"},
    {"sum_uint_array", "其他", "数组元素求和", "sum_uint_array(unsigned int arr[], int size)"},
    {"avg_uint_array", "其他", "数组平均值", "avg_uint_array(unsigned int arr[], int size)"},
    {"max_uint_array", "其他", "数组最大值", "max_uint_array(unsigned int arr[], int size)"},
    {"min_uint_array", "其他", "数组最小值", "min_uint_array(unsigned int arr[], int size)"},
    {"fill_uint_array", "其他", "用指定值填充数组", "fill_uint_array(unsigned int arr[], int size, unsigned int value)"},
    {"reverse_uint_array", "其他", "反转数组", "reverse_uint_array(unsigned int arr[], int size)"},
    {"find_uint_array", "其他", "查找元素下标", "find_uint_array(unsigned int arr[], int size, unsigned int target)"},
    {"count_uint_array", "其他", "统计元素出现次数", "count_uint_array(unsigned int arr[], int size, unsigned int target)"},
    {"product_uint_array", "其他", "数组元素乘积", "product_uint_array(unsigned int arr[], int size)"},
    {"copy_uint_array", "其他", "复制数组(需free)", "copy_uint_array(unsigned int arr[], int size)"},
    {"second_max_uint_array", "其他", "第二大元素", "second_max_uint_array(unsigned int arr[], int size)"},
    {"second_min_uint_array", "其他", "第二小元素", "second_min_uint_array(unsigned int arr[], int size)"},
    {"is_sorted_asc_uint_array", "其他", "判断数组是否升序", "is_sorted_asc_uint_array(unsigned int arr[], int size)"},
    {"is_sorted_desc_uint_array", "其他", "判断数组是否降序", "is_sorted_desc_uint_array(unsigned int arr[], int size)"},
    {"print_float_array", "其他", "打印数组元素", "print_float_array(float arr[], int size)"},
    {"sum_float_array", "其他", "数组元素求和", "sum_float_array(float arr[], int size)"},
    {"avg_float_array", "其他", "数组平均值", "avg_float_array(float arr[], int size)"},
    {"max_float_array", "其他", "数组最大值", "max_float_array(float arr[], int size)"},
    {"min_float_array", "其他", "数组最小值", "min_float_array(float arr[], int size)"},
    {"fill_float_array", "其他", "用指定值填充数组", "fill_float_array(float arr[], int size, float value)"},
    {"reverse_float_array", "其他", "反转数组", "reverse_float_array(float arr[], int size)"},
    {"find_float_array", "其他", "查找元素下标", "find_float_array(float arr[], int size, float target)"},
    {"count_float_array", "其他", "统计元素出现次数", "count_float_array(float arr[], int size, float target)"},
    {"product_float_array", "其他", "数组元素乘积", "product_float_array(float arr[], int size)"},
    {"copy_float_array", "其他", "复制数组(需free)", "copy_float_array(float arr[], int size)"},
    {"max_abs_float_array", "其他", "最大绝对值", "max_abs_float_array(float arr[], int size)"},
    {"min_abs_float_array", "其他", "最小绝对值", "min_abs_float_array(float arr[], int size)"},
    {"second_max_float_array", "其他", "第二大元素", "second_max_float_array(float arr[], int size)"},
    {"second_min_float_array", "其他", "第二小元素", "second_min_float_array(float arr[], int size)"},
    {"is_sorted_asc_float_array", "其他", "判断数组是否升序", "is_sorted_asc_float_array(float arr[], int size)"},
    {"is_sorted_desc_float_array", "其他", "判断数组是否降序", "is_sorted_desc_float_array(float arr[], int size)"},
    {"sum_double_array", "其他", "数组元素求和", "sum_double_array(double arr[], int size)"},
    {"avg_double_array", "其他", "数组平均值", "avg_double_array(double arr[], int size)"},
    {"max_double_array", "其他", "数组最大值", "max_double_array(double arr[], int size)"},
    {"min_double_array", "其他", "数组最小值", "min_double_array(double arr[], int size)"},
    {"fill_double_array", "其他", "用指定值填充数组", "fill_double_array(double arr[], int size, double value)"},
    {"reverse_double_array", "其他", "反转数组", "reverse_double_array(double arr[], int size)"},
    {"find_double_array", "其他", "查找元素下标", "find_double_array(double arr[], int size, double target)"},
    {"count_double_array", "其他", "统计元素出现次数", "count_double_array(double arr[], int size, double target)"},
    {"product_double_array", "其他", "数组元素乘积", "product_double_array(double arr[], int size)"},
    {"copy_double_array", "其他", "复制数组(需free)", "copy_double_array(double arr[], int size)"},
    {"max_abs_double_array", "其他", "最大绝对值", "max_abs_double_array(double arr[], int size)"},
    {"min_abs_double_array", "其他", "最小绝对值", "min_abs_double_array(double arr[], int size)"},
    {"second_max_double_array", "其他", "第二大元素", "second_max_double_array(double arr[], int size)"},
    {"second_min_double_array", "其他", "第二小元素", "second_min_double_array(double arr[], int size)"},
    {"is_sorted_asc_double_array", "其他", "判断数组是否升序", "is_sorted_asc_double_array(double arr[], int size)"},
    {"is_sorted_desc_double_array", "其他", "判断数组是否降序", "is_sorted_desc_double_array(double arr[], int size)"},
    {"print_char_array", "其他", "打印数组元素", "print_char_array(char arr[], int size)"},
    {"sum_char_array", "其他", "数组元素求和", "sum_char_array(char arr[], int size)"},
    {"avg_char_array", "其他", "数组平均值", "avg_char_array(char arr[], int size)"},
    {"max_char_array", "其他", "数组最大值", "max_char_array(char arr[], int size)"},
    {"min_char_array", "其他", "数组最小值", "min_char_array(char arr[], int size)"},
    {"fill_char_array", "其他", "用指定值填充数组", "fill_char_array(char arr[], int size, char value)"},
    {"reverse_char_array", "其他", "反转数组", "reverse_char_array(char arr[], int size)"},
    {"find_char_array", "其他", "查找元素下标", "find_char_array(char arr[], int size, char target)"},
    {"count_char_array", "其他", "统计元素出现次数", "count_char_array(char arr[], int size, char target)"},
    {"product_char_array", "其他", "数组元素乘积", "product_char_array(char arr[], int size)"},
    {"copy_char_array", "其他", "复制数组(需free)", "copy_char_array(char arr[], int size)"},
    {"max_abs_char_array", "其他", "最大绝对值", "max_abs_char_array(char arr[], int size)"},
    {"min_abs_char_array", "其他", "最小绝对值", "min_abs_char_array(char arr[], int size)"},
    {"second_max_char_array", "其他", "第二大元素", "second_max_char_array(char arr[], int size)"},
    {"second_min_char_array", "其他", "第二小元素", "second_min_char_array(char arr[], int size)"},
    {"is_sorted_asc_char_array", "其他", "判断数组是否升序", "is_sorted_asc_char_array(char arr[], int size)"},
    {"is_sorted_desc_char_array", "其他", "判断数组是否降序", "is_sorted_desc_char_array(char arr[], int size)"},
    {"print_uint8_array", "其他", "打印数组元素", "print_uint8_array(uint8_t arr[], int size)"},
    {"sum_uint8_array", "其他", "数组元素求和", "sum_uint8_array(uint8_t arr[], int size)"},
    {"avg_uint8_array", "其他", "数组平均值", "avg_uint8_array(uint8_t arr[], int size)"},
    {"max_uint8_array", "其他", "数组最大值", "max_uint8_array(uint8_t arr[], int size)"},
    {"min_uint8_array", "其他", "数组最小值", "min_uint8_array(uint8_t arr[], int size)"},
    {"fill_uint8_array", "其他", "用指定值填充数组", "fill_uint8_array(uint8_t arr[], int size, uint8_t value)"},
    {"reverse_uint8_array", "其他", "反转数组", "reverse_uint8_array(uint8_t arr[], int size)"},
    {"find_uint8_array", "其他", "查找元素下标", "find_uint8_array(uint8_t arr[], int size, uint8_t target)"},
    {"count_uint8_array", "其他", "统计元素出现次数", "count_uint8_array(uint8_t arr[], int size, uint8_t target)"},
    {"product_uint8_array", "其他", "数组元素乘积", "product_uint8_array(uint8_t arr[], int size)"},
    {"copy_uint8_array", "其他", "复制数组(需free)", "copy_uint8_array(uint8_t arr[], int size)"},
    {"second_max_uint8_array", "其他", "第二大元素", "second_max_uint8_array(uint8_t arr[], int size)"},
    {"second_min_uint8_array", "其他", "第二小元素", "second_min_uint8_array(uint8_t arr[], int size)"},
    {"is_sorted_asc_uint8_array", "其他", "判断数组是否升序", "is_sorted_asc_uint8_array(uint8_t arr[], int size)"},
    {"is_sorted_desc_uint8_array", "其他", "判断数组是否降序", "is_sorted_desc_uint8_array(uint8_t arr[], int size)"},
    {"print_uint16_array", "其他", "打印数组元素", "print_uint16_array(uint16_t arr[], int size)"},
    {"sum_uint16_array", "其他", "数组元素求和", "sum_uint16_array(uint16_t arr[], int size)"},
    {"avg_uint16_array", "其他", "数组平均值", "avg_uint16_array(uint16_t arr[], int size)"},
    {"max_uint16_array", "其他", "数组最大值", "max_uint16_array(uint16_t arr[], int size)"},
    {"min_uint16_array", "其他", "数组最小值", "min_uint16_array(uint16_t arr[], int size)"},
    {"fill_uint16_array", "其他", "用指定值填充数组", "fill_uint16_array(uint16_t arr[], int size, uint16_t value)"},
    {"reverse_uint16_array", "其他", "反转数组", "reverse_uint16_array(uint16_t arr[], int size)"},
    {"find_uint16_array", "其他", "查找元素下标", "find_uint16_array(uint16_t arr[], int size, uint16_t target)"},
    {"count_uint16_array", "其他", "统计元素出现次数", "count_uint16_array(uint16_t arr[], int size, uint16_t target)"},
    {"product_uint16_array", "其他", "数组元素乘积", "product_uint16_array(uint16_t arr[], int size)"},
    {"copy_uint16_array", "其他", "复制数组(需free)", "copy_uint16_array(uint16_t arr[], int size)"},
    {"second_max_uint16_array", "其他", "第二大元素", "second_max_uint16_array(uint16_t arr[], int size)"},
    {"second_min_uint16_array", "其他", "第二小元素", "second_min_uint16_array(uint16_t arr[], int size)"},
    {"is_sorted_asc_uint16_array", "其他", "判断数组是否升序", "is_sorted_asc_uint16_array(uint16_t arr[], int size)"},
    {"is_sorted_desc_uint16_array", "其他", "判断数组是否降序", "is_sorted_desc_uint16_array(uint16_t arr[], int size)"},
    {"print_uint32_array", "其他", "打印数组元素", "print_uint32_array(uint32_t arr[], int size)"},
    {"sum_uint32_array", "其他", "数组元素求和", "sum_uint32_array(uint32_t arr[], int size)"},
    {"avg_uint32_array", "其他", "数组平均值", "avg_uint32_array(uint32_t arr[], int size)"},
    {"max_uint32_array", "其他", "数组最大值", "max_uint32_array(uint32_t arr[], int size)"},
    {"min_uint32_array", "其他", "数组最小值", "min_uint32_array(uint32_t arr[], int size)"},
    {"fill_uint32_array", "其他", "用指定值填充数组", "fill_uint32_array(uint32_t arr[], int size, uint32_t value)"},
    {"reverse_uint32_array", "其他", "反转数组", "reverse_uint32_array(uint32_t arr[], int size)"},
    {"find_uint32_array", "其他", "查找元素下标", "find_uint32_array(uint32_t arr[], int size, uint32_t target)"},
    {"count_uint32_array", "其他", "统计元素出现次数", "count_uint32_array(uint32_t arr[], int size, uint32_t target)"},
    {"product_uint32_array", "其他", "数组元素乘积", "product_uint32_array(uint32_t arr[], int size)"},
    {"copy_uint32_array", "其他", "复制数组(需free)", "copy_uint32_array(uint32_t arr[], int size)"},
    {"second_max_uint32_array", "其他", "第二大元素", "second_max_uint32_array(uint32_t arr[], int size)"},
    {"second_min_uint32_array", "其他", "第二小元素", "second_min_uint32_array(uint32_t arr[], int size)"},
    {"is_sorted_asc_uint32_array", "其他", "判断数组是否升序", "is_sorted_asc_uint32_array(uint32_t arr[], int size)"},
    {"is_sorted_desc_uint32_array", "其他", "判断数组是否降序", "is_sorted_desc_uint32_array(uint32_t arr[], int size)"},
    {"mean_double_array", "其他", "平均值(double数组)", "mean_double_array(double arr[], int size)"},
    {"median_double_array", "其他", "中位数(double数组)", "median_double_array(double arr[], int size)"},
    {"mode_int_array", "其他", "众数(int数组，返回出现最多的值)", "mode_int_array(int arr[], int size)"},
    {"variance_double_array", "其他", "方差(double数组)", "variance_double_array(double arr[], int size)"},
    {"stddev_double_array", "其他", "标准差(double数组)", "stddev_double_array(double arr[], int size)"},
    {"range_double_array", "其他", "极差(最大值-最小值)", "range_double_array(double arr[], int size)"},
    {"percentile_double_array", "其他", "分位数(p为0~1)", "percentile_double_array(double arr[], int size, double p)"},
    {"geometric_mean_double", "其他", "几何平均数", "geometric_mean_double(double arr[], int size)"},
    {"harmonic_mean_double", "其他", "调和平均数", "harmonic_mean_double(double arr[], int size)"},
    {"has_duplicates_int", "其他", "数组是否有重复", "has_duplicates_int(int arr[], int size)"},
    {"all_positive_int", "其他", "数组是否全部为正", "all_positive_int(int arr[], int size)"},
    {"all_negative_int", "其他", "数组是否全部为负", "all_negative_int(int arr[], int size)"},
    {"all_even_int", "其他", "数组是否全部为偶数", "all_even_int(int arr[], int size)"},
    {"all_odd_int", "其他", "数组是否全部为奇数", "all_odd_int(int arr[], int size)"},
    {"count_greater_int", "其他", "统计大于 value 的元素个数", "count_greater_int(int arr[], int size, int value)"},
    {"count_less_int", "其他", "统计小于 value 的元素个数", "count_less_int(int arr[], int size, int value)"},
    {"count_between_int", "其他", "统计区间 [lo,hi] 内元素个数", "count_between_int(int arr[], int size, int lo, int hi)"},
    {"count_even_int", "其他", "统计偶数个数", "count_even_int(int arr[], int size)"},
    {"count_odd_int", "其他", "统计奇数个数", "count_odd_int(int arr[], int size)"},
    {"count_positive_int", "其他", "统计正数个数", "count_positive_int(int arr[], int size)"},
    {"count_negative_int", "其他", "统计负数个数", "count_negative_int(int arr[], int size)"},
    {"count_zero_int", "其他", "统计零元素个数", "count_zero_int(int arr[], int size)"},
    {"contains_int", "其他", "数组是否包含 value", "contains_int(int arr[], int size, int value)"},
    {"arrays_equal_int", "其他", "两个数组是否相等", "arrays_equal_int(int a[], int b[], int size)"},
    {"is_subset_int", "其他", "a 是否为 b 的子集", "is_subset_int(int a[], int na, int b[], int nb)"},
    {"most_frequent_int", "其他", "出现次数最多的元素", "most_frequent_int(int arr[], int size)"},
    {"map_square_int", "其他", "每个元素平方(原地)", "map_square_int(int arr[], int size)"},
    {"map_negate_int", "其他", "每个元素取反(原地)", "map_negate_int(int arr[], int size)"},
    {"map_double_int", "其他", "每个元素翻倍(原地)", "map_double_int(int arr[], int size)"},
    {"map_add_int", "其他", "每个元素加 offset", "map_add_int(int arr[], int size, int offset)"},
    {"clip_array_int", "其他", "数组裁剪到 [lo,hi]", "clip_array_int(int arr[], int size, int lo, int hi)"},
    {"cumulative_sum_int", "其他", "前缀和(原地覆盖)", "cumulative_sum_int(int arr[], int size)"},
    {"cumulative_product_int", "其他", "前缀积(原地覆盖)", "cumulative_product_int(int arr[], int size)"},
    {"prefix_min_int", "其他", "前缀最小值(原地覆盖)", "prefix_min_int(int arr[], int size)"},
    {"prefix_max_int", "其他", "前缀最大值(原地覆盖)", "prefix_max_int(int arr[], int size)"},
    {"differences_int", "其他", "相邻元素差分(原地)", "differences_int(int arr[], int size)"},
    {"concat_int_arrays", "其他", "拼接两个数组(需free)", "concat_int_arrays(int a[], int na, int b[], int nb, int *out_size)"},
    {"shell_sort", "其他", "希尔排序", "shell_sort(int arr[], int size)"},
    {"cocktail_sort", "其他", "鸡尾酒排序", "cocktail_sort(int arr[], int size)"},
    {"gnome_sort", "其他", "侏儒排序", "gnome_sort(int arr[], int size)"},
    {"comb_sort", "其他", "梳排序", "comb_sort(int arr[], int size)"},
    {"cycle_sort", "其他", "圈排序", "cycle_sort(int arr[], int size)"},
    {"counting_sort", "其他", "计数排序(值域0~max_val)", "counting_sort(int arr[], int size, int max_val)"},
    {"radix_sort", "其他", "基数排序", "radix_sort(int arr[], int size)"},
    {"bitonic_sort", "其他", "双调排序", "bitonic_sort(int arr[], int size)"},
    {"lower_bound_int", "其他", "下界：第一个 >= target 的下标", "lower_bound_int(int arr[], int size, int target)"},
    {"upper_bound_int", "其他", "上界：第一个 > target 的下标", "upper_bound_int(int arr[], int size, int target)"},
    {"exponential_search", "其他", "指数查找(升序)", "exponential_search(int arr[], int size, int target)"},
    {"jump_search", "其他", "跳跃查找(升序，步长 sqrt)", "jump_search(int arr[], int size, int target)"},
    {"ternary_search_max", "其他", "三分查找(单峰数组最大值)", "ternary_search_max(double arr[], int size)"},
    {"binary_search_double", "其他", "浮点二分查找(升序)", "binary_search_double(double arr[], int size, double target)"},
    {"find_all_int", "其他", "线性查找全部匹配下标(需free)", "find_all_int(int arr[], int size, int target, int *count)"},
    {"str_upper_copy", "其他", "返回大写副本(需free)", "str_upper_copy(const char *str)"},
    {"str_lower_copy", "其他", "返回小写副本(需free)", "str_lower_copy(const char *str)"},
    {"str_reverse_copy", "其他", "返回反转副本(需free)", "str_reverse_copy(const char *str)"},
    {"str_trim_copy", "其他", "返回去空格副本(需free)", "str_trim_copy(const char *str)"},
    {"str_pad_left", "其他", "左侧补齐到 length 位", "str_pad_left(char *buf, int buf_size, char pad, int length)"},
    {"str_pad_right", "其他", "右侧补齐到 length 位", "str_pad_right(char *buf, int buf_size, char pad, int length)"},
    {"str_truncate", "其他", "截断到 max_len", "str_truncate(char *str, int max_len)"},
    {"str_repeat", "其他", "重复字符串 times 次写入 buf", "str_repeat(char *buf, int buf_size, const char *str, int times)"},
    {"str_count_substr", "其他", "统计子串出现次数", "str_count_substr(const char *str, const char *sub)"},
    {"str_is_alpha", "其他", "判断是否全为字母", "str_is_alpha(const char *str)"},
    {"str_is_digit", "其他", "判断是否全为数字", "str_is_digit(const char *str)"},
    {"str_is_alnum", "其他", "判断是否全为字母数字", "str_is_alnum(const char *str)"},
    {"str_is_lower", "其他", "判断是否全为小写", "str_is_lower(const char *str)"},
    {"str_is_upper", "其他", "判断是否全为大写", "str_is_upper(const char *str)"},
    {"str_swap_case", "其他", "大小写互换(原地)", "str_swap_case(char *str)"},
    {"str_title_case", "其他", "单词首字母大写(原地)", "str_title_case(char *str)"},
    {"str_remove_whitespace", "其他", "删除所有空白字符(原地)", "str_remove_whitespace(char *str)"},
    {"str_remove_vowels", "其他", "删除所有元音(原地)", "str_remove_vowels(char *str)"},
    {"str_are_anagrams", "其他", "是否互为字母异位词", "str_are_anagrams(const char *a, const char *b)"},
    {"str_is_subsequence", "其他", "是否为子序列", "str_is_subsequence(const char *s, const char *t)"},
    {"str_left", "其他", "取前 n 个字符", "str_left(const char *str, int n, char *buf, int buf_size)"},
    {"str_right", "其他", "取后 n 个字符", "str_right(const char *str, int n, char *buf, int buf_size)"},
    {"str_count_lines", "其他", "统计行数", "str_count_lines(const char *str)"},
    {"str_longest_word_len", "其他", "最长单词长度", "str_longest_word_len(const char *str)"},
    {"str_most_common_char", "其他", "出现最多的字符", "str_most_common_char(const char *str)"},
    {"str_count_vowels", "其他", "统计元音个数", "str_count_vowels(const char *str)"},
    {"str_caesar_shift", "其他", "凯撒加密(原地)", "str_caesar_shift(char *str, int shift)"},
    {"str_rot13", "其他", "ROT13 加密(原地)", "str_rot13(char *str)"},
    {"is_upper_char", "其他", "是否大写字母", "is_upper_char(char c)"},
    {"is_lower_char", "其他", "是否小写字母", "is_lower_char(char c)"},
    {"is_hex_char", "其他", "是否十六进制字符", "is_hex_char(char c)"},
    {"is_octal_char", "其他", "是否八进制字符", "is_octal_char(char c)"},
    {"is_printable_char", "其他", "是否可打印字符", "is_printable_char(char c)"},
    {"is_punctuation_char", "其他", "是否标点字符", "is_punctuation_char(char c)"},
    {"is_vowel_char", "其他", "是否元音", "is_vowel_char(char c)"},
    {"is_consonant_char", "其他", "是否辅音", "is_consonant_char(char c)"},
    {"next_char", "其他", "下一个字符", "next_char(char c)"},
    {"prev_char", "其他", "上一个字符", "prev_char(char c)"},
    {"char_rotate", "其他", "字符循环右移 n", "char_rotate(char c, int n)"},
    {"digit_char_to_int", "其他", "数字字符转数值", "digit_char_to_int(char c)"},
    {"int_to_digit_char", "其他", "数值转数字字符(0~9)", "int_to_digit_char(int v)"},
    {"is_even", "其他", "是否偶数", "is_even(int n)"},
    {"is_odd", "其他", "是否奇数", "is_odd(int n)"},
    {"is_square", "其他", "是否完全平方数", "is_square(int n)"},
    {"is_cube", "其他", "是否完全立方数", "is_cube(int n)"},
    {"digital_root", "其他", "数字根(数位反复求和)", "digital_root(int n)"},
    {"nth_prime", "其他", "第 n 个素数", "nth_prime(int n)"},
    {"next_prime", "其他", "下一个素数(大于 n)", "next_prime(int n)"},
    {"prev_prime", "其他", "上一个素数(小于 n)", "prev_prime(int n)"},
    {"count_primes_upto", "其他", "n 以内素数个数", "count_primes_upto(int n)"},
    {"sum_primes_upto", "其他", "n 以内素数之和", "sum_primes_upto(int n)"},
    {"binomial_coefficient", "其他", "组合数 C(n,r)", "binomial_coefficient(int n, int r)"},
    {"permutation_count", "其他", "排列数 P(n,r)", "permutation_count(int n, int r)"},
    {"harmonic_number", "其他", "第 n 个调和数", "harmonic_number(int n)"},
    {"is_abundant", "其他", "是否盈数(真因子和>自身)", "is_abundant(int n)"},
    {"is_deficient", "其他", "是否亏数", "is_deficient(int n)"},
    {"is_amicable", "其他", "是否亲和数对(a,b)", "is_amicable(int a, int b)"},
    {"is_happy", "其他", "是否快乐数", "is_happy(int n)"},
    {"is_harshad", "其他", "是否哈沙德数(可被数位和整除)", "is_harshad(int n)"},
    {"is_kaprekar", "其他", "是否卡普雷卡数", "is_kaprekar(int n)"},
    {"is_automorphic", "其他", "是否自守数", "is_automorphic(int n)"},
    {"is_triangular", "其他", "是否三角形数", "is_triangular(int n)"},
    {"collatz_steps", "其他", "科拉兹猜想步数", "collatz_steps(int n)"},
    {"aliquot_sum", "其他", "真因子之和(别名)", "aliquot_sum(int n)"},
    {"count_divisors", "其他", "因子个数", "count_divisors(int n)"},
    {"sum_divisors", "其他", "因子之和", "sum_divisors(int n)"},
    {"euler_phi", "其他", "欧拉函数 φ(n)", "euler_phi(int n)"},
    {"double_factorial", "其他", "双阶乘 n!!", "double_factorial(int n)"},
    {"catalan_number", "其他", "第 n 个卡塔兰数", "catalan_number(int n)"},
    {"hanoi_moves", "其他", "n 个圆盘汉诺塔最少步数", "hanoi_moves(int n)"},
    {"josephus", "其他", "约瑟夫环幸存者", "josephus(int n, int k)"},
    {"radians_to_degrees", "其他", "弧度转角度", "radians_to_degrees(double rad)"},
    {"degrees_to_radians", "其他", "角度转弧度", "degrees_to_radians(double deg)"},
    {"sigmoid", "其他", "Sigmoid 函数", "sigmoid(double x)"},
    {"relu", "其他", "ReLU 函数", "relu(double x)"},
    {"angle_normalize", "其他", "角度归一化到 [0,360)", "angle_normalize(double deg)"},
    {"round_half_up", "其他", "四舍五入(到整数)", "round_half_up(double x)"},
    {"percentage", "其他", "百分比", "percentage(double part, double total)"},
    {"median_of_three", "其他", "三个数的中位数", "median_of_three(double a, double b, double c)"},
    {"weighted_average", "其他", "加权平均", "weighted_average(double values[], double weights[], int size)"},
    {"int_to_base_str", "其他", "十进制转任意进制(2~36)", "int_to_base_str(int num, int base, char *buf, int buf_size)"},
    {"base_str_to_int", "其他", "任意进制字符串转十进制", "base_str_to_int(const char *str, int base)"},
    {"str_to_long", "其他", "字符串转 long", "str_to_long(const char *str)"},
    {"str_to_double", "其他", "字符串转 double", "str_to_double(const char *str)"},
    {"double_to_str", "其他", "double 转字符串", "double_to_str(double num, char *buf)"},
    {"int_to_roman", "其他", "十进制转罗马数字", "int_to_roman(int num, char *buf, int buf_size)"},
    {"roman_to_int", "其他", "罗马数字转十进制", "roman_to_int(const char *s)"},
    {"format_thousands", "其他", "千位分隔符格式化", "format_thousands(long long num, char *buf, int buf_size)"},
    {"format_bytes", "其他", "字节大小格式化(KB/MB/GB)", "format_bytes(long long bytes, char *buf, int buf_size)"},
    {"get_bit", "其他", "读取第 bit 位(0/1)", "get_bit(uint32_t val, int bit)"},
    {"set_bit_value", "其他", "把第 bit 位设为 value(0/1)", "set_bit_value(uint32_t val, int bit, int value)"},
    {"count_zeros", "其他", "统计 0 的个数", "count_zeros(uint32_t val)"},
    {"msb_position", "其他", "最高位 1 的位置(0~31)", "msb_position(uint32_t val)"},
    {"next_power_of_two", "其他", "下一个 2 的幂", "next_power_of_two(uint32_t n)"},
    {"prev_power_of_two", "其他", "上一个 2 的幂", "prev_power_of_two(uint32_t n)"},
    {"reverse_bits", "其他", "反转二进制位", "reverse_bits(uint32_t val)"},
    {"nibble_high", "其他", "取高 4 位", "nibble_high(uint8_t val)"},
    {"nibble_low", "其他", "取低 4 位", "nibble_low(uint8_t val)"},
    {"nibble_swap", "其他", "交换高低 4 位", "nibble_swap(uint8_t val)"},
    {"bit_field_get", "其他", "取位域(从 start 起 len 位)", "bit_field_get(uint32_t val, int start, int len)"},
    {"bit_field_set", "其他", "把位域写入(从 start 起 len 位)", "bit_field_set(uint32_t val, int start, int len, uint32_t data)"},
    {"low_bit_mask", "其他", "生成低 n 位全 1 掩码", "low_bit_mask(int n)"},
    {"high_bit_mask", "其他", "生成高 n 位全 1 掩码", "high_bit_mask(int n)"},
    {"swap_no_temp", "其他", "无临时变量交换", "swap_no_temp(int *a, int *b)"},
    {"is_mask_contiguous", "其他", "判断二进制是否为连续 1", "is_mask_contiguous(uint32_t val)"},
    {"sign_int", "其他", "整数符号(1/-1/0)", "sign_int(int n)"},
    {"crc16_ccitt", "其他", "CRC-16/CCITT", "crc16_ccitt(const uint8_t *data, uint16_t len)"},
    {"crc16_xmodem", "其他", "CRC-16/XMODEM", "crc16_xmodem(const uint8_t *data, uint16_t len)"},
    {"crc32", "其他", "CRC-32", "crc32(const uint8_t *data, uint16_t len)"},
    {"fletcher16", "其他", "Fletcher-16 校验", "fletcher16(const uint8_t *data, uint16_t len)"},
    {"fletcher32", "其他", "Fletcher-32 校验", "fletcher32(const uint16_t *data, uint16_t len)"},
    {"adler32", "其他", "Adler-32 校验", "adler32(const uint8_t *data, uint16_t len)"},
    {"lrc_checksum", "其他", "LRC 纵向冗余校验", "lrc_checksum(const uint8_t *data, uint16_t len)"},
    {"weighted_checksum", "其他", "加权校验和", "weighted_checksum(const uint8_t *data, uint16_t len)"},
    {"nmea_checksum", "其他", "NMEA 校验($ 与 * 之间异或)", "nmea_checksum(const char *sentence)"},
    {"rshash", "其他", "RS 哈希", "rshash(const char *str)"},
    {"jshash", "其他", "JS 哈希", "jshash(const char *str)"},
    {"pjwhash", "其他", "PJW 哈希", "pjwhash(const char *str)"},
    {"elfhash", "其他", "ELF 哈希", "elfhash(const char *str)"},
    {"aphash", "其他", "AP 哈希", "aphash(const char *str)"},
    {"java_hash", "其他", "Java 字符串哈希", "java_hash(const char *str)"},
    {"djb2_xor_hash", "其他", "DJB2-XOR 哈希", "djb2_xor_hash(const char *str)"},
    {"fnv1_hash", "其他", "FNV-1 哈希", "fnv1_hash(const char *str)"},
    {"dekhash", "其他", "DEK 哈希", "dekhash(const char *str)"},
    {"bphash", "其他", "BP 哈希", "bphash(const char *str)"},
    {"bkdr_hash_seed", "其他", "BKDR 哈希(可指定种子)", "bkdr_hash_seed(const char *str, uint32_t seed)"},
    {"is_valid_date", "其他", "判断日期是否有效", "is_valid_date(int year, int month, int day)"},
    {"days_in_month", "其他", "某月天数", "days_in_month(int year, int month)"},
    {"day_of_year", "其他", "一年中的第几天", "day_of_year(int year, int month, int day)"},
    {"days_in_year", "其他", "一年有多少天", "days_in_year(int year)"},
    {"get_year_now", "其他", "当前年", "get_year_now(void)"},
    {"get_month_now", "其他", "当前月(1~12)", "get_month_now(void)"},
    {"get_day_now", "其他", "当前日(1~31)", "get_day_now(void)"},
    {"get_hour_now", "其他", "当前小时(0~23)", "get_hour_now(void)"},
    {"get_minute_now", "其他", "当前分钟(0~59)", "get_minute_now(void)"},
    {"get_second_now", "其他", "当前秒(0~59)", "get_second_now(void)"},
    {"get_weekday_now", "其他", "当前星期几(0=周日)", "get_weekday_now(void)"},
    {"timestamp_to_date_str", "其他", "时间戳转日期字符串", "timestamp_to_date_str(long long ts, char *buf, int buf_size)"},
    {"rand_seed_time", "其他", "用当前时间设置随机种子", "rand_seed_time(void)"},
    {"rand_bool", "其他", "随机布尔值", "rand_bool(void)"},
    {"rand_double", "其他", "随机浮点数 [0,1)", "rand_double(void)"},
    {"rand_double_range", "其他", "随机浮点数 [min,max)", "rand_double_range(double min, double max)"},
    {"rand_choice_int", "其他", "随机选择数组元素", "rand_choice_int(int arr[], int size)"},
    {"rand_string", "其他", "生成随机字符串(可打印字符)", "rand_string(char *buf, int buf_size, int len)"},
    {"rand_digits_string", "其他", "生成随机数字字符串", "rand_digits_string(char *buf, int buf_size, int len)"},
    {"rand_shuffle_str", "其他", "打乱字符串(原地)", "rand_shuffle_str(char *str)"},
    {"rand_unique_ints", "其他", "在 [min,max] 生成 n 个不重复随机数", "rand_unique_ints(int min, int max, int n)"},
    {"distance_2d", "其他", "二维两点距离", "distance_2d(double x1, double y1, double x2, double y2)"},
    {"distance_3d", "其他", "三维两点距离", "distance_3d(double x1, double y1, double z1, double x2, double y2, double z2)"},
    {"area_triangle_heron", "其他", "海伦公式三角形面积", "area_triangle_heron(double a, double b, double c)"},
    {"perimeter_triangle", "其他", "三角形周长", "perimeter_triangle(double a, double b, double c)"},
    {"circle_area", "其他", "圆面积", "circle_area(double r)"},
    {"circle_circumference", "其他", "圆周长", "circle_circumference(double r)"},
    {"circle_diameter", "其他", "圆直径", "circle_diameter(double r)"},
    {"sphere_volume", "其他", "球体积", "sphere_volume(double r)"},
    {"sphere_surface_area", "其他", "球表面积", "sphere_surface_area(double r)"},
    {"rect_area", "其他", "矩形面积", "rect_area(double w, double h)"},
    {"rect_perimeter", "其他", "矩形周长", "rect_perimeter(double w, double h)"},
    {"is_point_in_rect", "其他", "点是否在矩形内", "is_point_in_rect(double px, double py, double x, double y, double w, double h)"},
    {"is_point_in_circle", "其他", "点是否在圆内", "is_point_in_circle(double px, double py, double cx, double cy, double r)"},
    {"slope_between", "其他", "两点斜率", "slope_between(double x1, double y1, double x2, double y2)"},
    {"midpoint_2d", "其他", "二维中点", "midpoint_2d(double x1, double y1, double x2, double y2, double *mx, double *my)"},
    {"hexagon_area", "其他", "正六边形面积", "hexagon_area(double side)"},
    {"cylinder_volume", "其他", "圆柱体积", "cylinder_volume(double r, double h)"},
    {"clamp_int", "其他", "整数裁剪到 [lo,hi]", "clamp_int(int v, int lo, int hi)"},
    {"clamp_double", "其他", "浮点裁剪到 [lo,hi]", "clamp_double(double v, double lo, double hi)"},
    {"lerp_double", "其他", "线性插值", "lerp_double(double a, double b, double t)"},
    {"lerp_int", "其他", "整数线性插值", "lerp_int(int a, int b, int t, int max_t)"},
    {"map_range_double", "其他", "数值映射(从 [s1,s2] 到 [d1,d2])", "map_range_double(double v, double s1, double s2, double d1, double d2)"},
    {"round_to_int", "其他", "取整到最近整数", "round_to_int(double x)"},
    {"ceil_to_multiple", "其他", "向上取整到 m 的倍数", "ceil_to_multiple(long long v, long long m)"},
    {"floor_to_multiple", "其他", "向下取整到 m 的倍数", "floor_to_multiple(long long v, long long m)"},
    {"approx_equal_double", "其他", "是否近似相等(误差 eps)", "approx_equal_double(double a, double b, double eps)"},
    {"max3_int", "其他", "三数最大值", "max3_int(int a, int b, int c)"},
    {"min3_int", "其他", "三数最小值", "min3_int(int a, int b, int c)"},
    {"max4_int", "其他", "四数最大值", "max4_int(int a, int b, int c, int d)"},
    {"fabs_double", "其他", "浮点绝对值", "fabs_double(double x)"},
    {"floor_int", "其他", "高斯取整(向下取整)", "floor_int(double x)"},
    {"ceil_int", "其他", "向上取整", "ceil_int(double x)"},
    {"sum_natural", "其他", "自然数 1..n 之和", "sum_natural(int n)"},
    {"sum_squares", "其他", "平方和 1^2+..+n^2", "sum_squares(int n)"},
    {"sum_cubes", "其他", "立方和 1^3+..+n^3", "sum_cubes(int n)"},
    {"arithmetic_sum", "其他", "等差数列前 n 项和", "arithmetic_sum(long long a1, long long d, int n)"},
    {"dlist_create", "其他", "创建空双向链表", "dlist_create(void)"},
    {"dlist_push_front", "其他", "头部插入", "dlist_push_front(DList *l, int data)"},
    {"dlist_push_back", "其他", "尾部插入", "dlist_push_back(DList *l, int data)"},
    {"dlist_remove", "其他", "删除第一个等于 data 的节点", "dlist_remove(DList *l, int data)"},
    {"dlist_search", "其他", "查找节点", "dlist_search(DList *l, int data)"},
    {"dlist_length", "其他", "链表长度", "dlist_length(DList *l)"},
    {"dlist_print", "其他", "正序打印", "dlist_print(DList *l)"},
    {"dlist_reverse", "其他", "反转链表", "dlist_reverse(DList *l)"},
    {"dlist_free", "其他", "释放链表", "dlist_free(DList *l)"},
    {"deque_create", "其他", "创建双端队列", "deque_create(int capacity)"},
    {"deque_destroy", "其他", "销毁双端队列", "deque_destroy(Deque *d)"},
    {"deque_push_front", "其他", "头部入队", "deque_push_front(Deque *d, int value)"},
    {"deque_push_back", "其他", "尾部入队", "deque_push_back(Deque *d, int value)"},
    {"deque_pop_front", "其他", "头部出队", "deque_pop_front(Deque *d, int *out)"},
    {"deque_pop_back", "其他", "尾部出队", "deque_pop_back(Deque *d, int *out)"},
    {"deque_peek_front", "其他", "查看头部", "deque_peek_front(Deque *d, int *out)"},
    {"deque_peek_back", "其他", "查看尾部", "deque_peek_back(Deque *d, int *out)"},
    {"deque_size", "其他", "元素个数", "deque_size(Deque *d)"},
    {"deque_is_empty", "其他", "是否为空", "deque_is_empty(Deque *d)"},
    {"deque_is_full", "其他", "是否已满", "deque_is_full(Deque *d)"},
    {"deque_clear", "其他", "清空", "deque_clear(Deque *d)"},
    {"mheap_create", "其他", "创建最小堆", "mheap_create(int capacity)"},
    {"mheap_destroy", "其他", "销毁最小堆", "mheap_destroy(MinHeap *h)"},
    {"mheap_push", "其他", "入堆", "mheap_push(MinHeap *h, int value)"},
    {"mheap_pop", "其他", "弹出最小值", "mheap_pop(MinHeap *h, int *out)"},
    {"mheap_peek", "其他", "查看最小值", "mheap_peek(MinHeap *h, int *out)"},
    {"mheap_size", "其他", "堆大小", "mheap_size(MinHeap *h)"},
    {"mheap_is_empty", "其他", "堆是否为空", "mheap_is_empty(MinHeap *h)"},
    {"iset_create", "其他", "创建整数集合", "iset_create(int capacity)"},
    {"iset_destroy", "其他", "销毁整数集合", "iset_destroy(IntSet *s)"},
    {"iset_add", "其他", "添加元素", "iset_add(IntSet *s, int key)"},
    {"iset_contains", "其他", "是否包含元素", "iset_contains(IntSet *s, int key)"},
    {"iset_remove", "其他", "删除元素", "iset_remove(IntSet *s, int key)"},
    {"iset_size", "其他", "元素个数", "iset_size(IntSet *s)"},
    {"iset_clear", "其他", "清空集合", "iset_clear(IntSet *s)"},
    {"smap_create", "其他", "创建字符串哈希表", "smap_create(int capacity)"},
    {"smap_destroy", "其他", "销毁哈希表", "smap_destroy(StrMap *m)"},
    {"smap_put", "其他", "写入键值对", "smap_put(StrMap *m, const char *key, int value)"},
    {"smap_get", "其他", "读取键对应的值", "smap_get(StrMap *m, const char *key, int *out)"},
    {"smap_contains", "其他", "是否包含键", "smap_contains(StrMap *m, const char *key)"},
    {"smap_remove", "其他", "删除键", "smap_remove(StrMap *m, const char *key)"},
    {"smap_size", "其他", "键值对数量", "smap_size(StrMap *m)"},
    {"graph_create", "其他", "创建 n 个节点的图", "graph_create(int n)"},
    {"graph_destroy", "其他", "销毁图", "graph_destroy(Graph *g)"},
    {"graph_add_edge", "其他", "添加无向边", "graph_add_edge(Graph *g, int u, int v)"},
    {"graph_remove_edge", "其他", "删除无向边", "graph_remove_edge(Graph *g, int u, int v)"},
    {"graph_has_edge", "其他", "是否有边", "graph_has_edge(Graph *g, int u, int v)"},
    {"graph_degree", "其他", "节点度数", "graph_degree(Graph *g, int v)"},
    {"graph_print", "其他", "打印邻接矩阵", "graph_print(Graph *g)"},
    {"graph_bfs", "其他", "广度优先遍历(打印)", "graph_bfs(Graph *g, int start)"},
    {"graph_dfs", "其他", "深度优先遍历(打印)", "graph_dfs(Graph *g, int start)"},
    {"graph_dijkstra", "其他", "Dijkstra 单源最短路(需free)", "graph_dijkstra(Graph *g, int src)"},
    {"file_append_line", "其他", "追加一行", "file_append_line(const char *filename, const char *line)"},
    {"file_is_empty", "其他", "文件是否为空", "file_is_empty(const char *filename)"},
    {"file_touch", "其他", "创建空文件", "file_touch(const char *filename)"},
    {"file_delete", "其他", "删除文件", "file_delete(const char *filename)"},
    {"file_rename", "其他", "重命名文件", "file_rename(const char *old, const char *new)"},
    {"file_stem", "其他", "取文件主名(不含扩展名)", "file_stem(const char *path, char *buf, int buf_size)"},
    {"file_read_line", "其他", "读取一行到缓冲区", "file_read_line(FILE *fp, char *buf, int buf_size)"},
    {"safe_memdup", "其他", "复制内存块(需free)", "safe_memdup(const void *src, size_t size)"},
    {"zero_memory", "其他", "内存清零", "zero_memory(void *ptr, size_t size)"},
    {"fill_memory", "其他", "内存填充", "fill_memory(void *ptr, size_t size, unsigned char value)"},
    {"compare_memory", "其他", "内存比较", "compare_memory(const void *a, const void *b, size_t size)"},
    {"swap_memory", "其他", "交换内存块", "swap_memory(void *a, void *b, size_t size)"},
    {"print_int", "其他", "打印整数", "print_int(int v)"},
    {"print_long", "其他", "打印长整数", "print_long(long v)"},
    {"print_double", "其他", "打印浮点数", "print_double(double v)"},
    {"print_hex", "其他", "打印十六进制", "print_hex(unsigned int v)"},
    {"print_char", "其他", "打印单个字符", "print_char(char c)"},
    {"print_separator", "其他", "打印分隔线", "print_separator(void)"},
    {"print_box_title", "其他", "打印带边框标题", "print_box_title(const char *title)"},
    {"print_str_array", "其他", "打印字符串数组", "print_str_array(char *arr[], int size)"},
    {"clear_console", "其他", "清空控制台", "clear_console(void)"},
    {"log_info", "其他", "打印信息日志", "log_info(const char *msg)"},
    {"log_warn", "其他", "打印警告日志", "log_warn(const char *msg)"},
    {"log_error", "其他", "打印错误日志", "log_error(const char *msg)"},
    {"mat_create", "其他", "创建 rows x cols 双精度矩阵", "mat_create(int rows, int cols)"},
    {"mat_free", "其他", "释放矩阵", "mat_free(double **m, int rows)"},
    {"mat_fill", "其他", "用值填充矩阵", "mat_fill(double **m, int rows, int cols, double v)"},
    {"mat_print", "其他", "打印矩阵", "mat_print(double **m, int rows, int cols)"},
    {"mat_transpose", "其他", "矩阵转置(写入 out)", "mat_transpose(double **m, int rows, int cols, double **out)"},
    {"mat_add", "其他", "矩阵加法(out = a + b)", "mat_add(double **a, double **b, int rows, int cols, double **out)"},
    {"mat_sub", "其他", "矩阵减法(out = a - b)", "mat_sub(double **a, double **b, int rows, int cols, double **out)"},
    {"mat_mul", "其他", "矩阵乘法(out = a * b)", "mat_mul(double **a, int ar, int ac, double **b, int bc, double **out)"},
    {"mat_identity", "其他", "单位矩阵", "mat_identity(double **m, int n)"},
    {"mat_scalar_mul", "其他", "数乘矩阵", "mat_scalar_mul(double **m, int rows, int cols, double s, double **out)"},
    {"mat_trace", "其他", "方阵迹(对角线之和)", "mat_trace(double **m, int n)"},
    {"mat_det2", "其他", "2x2 行列式", "mat_det2(double **m)"},
    {"mat_det3", "其他", "3x3 行列式", "mat_det3(double **m)"},
    {"mat_sum", "其他", "矩阵元素和", "mat_sum(double **m, int rows, int cols)"},
    {"mat_max", "其他", "矩阵最大值", "mat_max(double **m, int rows, int cols)"},
    {"mat_min", "其他", "矩阵最小值", "mat_min(double **m, int rows, int cols)"},
    {"mat_row_sum", "其他", "行元素和", "mat_row_sum(double **m, int cols, int row)"},
    {"mat_col_sum", "其他", "列元素和", "mat_col_sum(double **m, int rows, int col)"},
    {"mat_copy", "其他", "复制矩阵", "mat_copy(double **m, int rows, int cols)"},
    {"dot_product", "其他", "向量点积", "dot_product(double a[], double b[], int size)"},
    {"vector_length_2d", "其他", "二维向量长度", "vector_length_2d(double x, double y)"},
    {"vector_length_3d", "其他", "三维向量长度", "vector_length_3d(double x, double y, double z)"},
    {"normalize_2d", "其他", "二维向量归一化(写入 out)", "normalize_2d(double x, double y, double *ox, double *oy)"},
    {"cross_product_2d", "其他", "二维叉积(带符号面积)", "cross_product_2d(double ax, double ay, double bx, double by)"},
    {"moving_average", "其他", "移动平均(写入 out)", "moving_average(double arr[], int size, int window, double out[])"},
    {"int_array_to_double", "其他", "整数数组转 double 数组", "int_array_to_double(int src[], double dst[], int size)"},
    {"double_array_to_int", "其他", "double 数组转 int 数组", "double_array_to_int(double src[], int dst[], int size)"},
    {"base64_encode", "其他", "Base64 编码(需free)", "base64_encode(const uint8_t *data, int len)"},
    {"base64_decode", "其他", "Base64 解码(需free)", "base64_decode(const char *s, int *out_len)"},
    {"url_encode_str", "其他", "URL 编码(需free)", "url_encode_str(const char *s)"},
    {"str_contains_ignore_case", "其他", "忽略大小写判断是否包含子串", "str_contains_ignore_case(const char *haystack, const char *needle)"},
    {"str_compare_case_insensitive", "其他", "忽略大小写比较字符串", "str_compare_case_insensitive(const char *a, const char *b)"},
    {"str_is_palindrome_ignore_case", "其他", "忽略大小写判断回文", "str_is_palindrome_ignore_case(const char *str)"},
    {"str_reverse_each_word", "其他", "反转每个单词内部的字母", "str_reverse_each_word(char *str)"},
    {"str_shift_left", "其他", "字符串左循环移动 n 位", "str_shift_left(char *str, int n)"},
    {"str_shift_right", "其他", "字符串右循环移动 n 位", "str_shift_right(char *str, int n)"},
    {"str_deduplicate_chars", "其他", "去除相邻重复字符", "str_deduplicate_chars(char *str)"},
    {"str_remove_consonants", "其他", "删除所有辅音字母", "str_remove_consonants(char *str)"},
    {"str_count_consonants", "其他", "统计辅音字母个数", "str_count_consonants(const char *str)"},
    {"str_append_char", "其他", "尾部追加一个字符", "str_append_char(char *buf, int buf_size, char c)"},
    {"str_remove_first_char", "其他", "删除第一个字符", "str_remove_first_char(char *str)"},
    {"str_remove_last_char", "其他", "删除最后一个字符", "str_remove_last_char(char *str)"},
    {"str_find_nth", "其他", "查找第 n 次出现的子串下标(0起)", "str_find_nth(const char *str, const char *sub, int n)"},
    {"str_count_digits", "其他", "统计数字字符个数", "str_count_digits(const char *str)"},
    {"str_count_letters", "其他", "统计字母个数", "str_count_letters(const char *str)"},
    {"str_count_uppercase", "其他", "统计大写字母个数", "str_count_uppercase(const char *str)"},
    {"str_count_lowercase", "其他", "统计小写字母个数", "str_count_lowercase(const char *str)"},
    {"str_count_spaces", "其他", "统计空格个数", "str_count_spaces(const char *str)"},
    {"str_normalize_spaces", "其他", "把连续多个空格合并为一个", "str_normalize_spaces(char *str)"},
    {"str_abbreviate", "其他", "取每个单词首字母缩写", "str_abbreviate(const char *str, char *buf, int buf_size)"},
    {"str_word_at", "其他", "提取第 n 个单词(0起)", "str_word_at(const char *str, int n, char *buf, int buf_size)"},
    {"str_mask_sensitive", "其他", "敏感信息打码(保留后4位)", "str_mask_sensitive(const char *str, char *buf, int buf_size)"},
    {"str_is_valid_email", "其他", "简单邮箱格式校验", "str_is_valid_email(const char *s)"},
    {"str_count_sentences", "其他", "统计句子数(. ! ?)", "str_count_sentences(const char *str)"},
    {"str_longest_palindrome_substr_len", "其他", "最长回文子串长度(动态规划)", "str_longest_palindrome_substr_len(const char *s)"},
    {"str_reverse_vowels", "其他", "反转元音字母顺序", "str_reverse_vowels(char *str)"},
    {"str_remove_digits", "其他", "删除所有数字", "str_remove_digits(char *str)"},
    {"str_keep_digits_only", "其他", "只保留数字", "str_keep_digits_only(char *str)"},
    {"str_keep_letters_only", "其他", "只保留字母", "str_keep_letters_only(char *str)"},
    {"str_fill", "其他", "用字符填满缓冲区", "str_fill(char *buf, int buf_size, char c, int len)"},
    {"str_swap_chars", "其他", "交换两个位置的字符", "str_swap_chars(char *str, int i, int j)"},
    {"str_shortest_word_len", "其他", "最短单词长度", "str_shortest_word_len(const char *str)"},
    {"str_avg_word_len", "其他", "平均单词长度", "str_avg_word_len(const char *str)"},
    {"str_is_empty", "其他", "字符串是否为空", "str_is_empty(const char *str)"},
    {"gcd3", "其他", "三数最大公约数", "gcd3(int a, int b, int c)"},
    {"gcd4", "其他", "四数最大公约数", "gcd4(int a, int b, int c, int d)"},
    {"lcm3", "其他", "三数最小公倍数", "lcm3(int a, int b, int c)"},
    {"is_relatively_prime", "其他", "是否互质", "is_relatively_prime(int a, int b)"},
    {"mod_add", "其他", "模加法 (a+b)%m", "mod_add(long long a, long long b, long long m)"},
    {"mod_sub", "其他", "模减法 (a-b)%m", "mod_sub(long long a, long long b, long long m)"},
    {"mod_mul", "其他", "模乘法 (a*b)%m", "mod_mul(long long a, long long b, long long m)"},
    {"mod_inverse", "其他", "模逆元(需互质，否则-1)", "mod_inverse(int a, int m)"},
    {"fast_fibonacci", "其他", "快速加倍法求斐波那契", "fast_fibonacci(int n)"},
    {"integer_sqrt", "其他", "整数平方根", "integer_sqrt(int n)"},
    {"integer_cbrt", "其他", "整数立方根", "integer_cbrt(int n)"},
    {"log2_floor", "其他", "log2 向下取整", "log2_floor(int n)"},
    {"log10_floor", "其他", "log10 向下取整", "log10_floor(int n)"},
    {"factorial_mod", "其他", "阶乘取模 n! % m", "factorial_mod(int n, long long m)"},
    {"is_fibonacci_number", "其他", "是否为斐波那契数", "is_fibonacci_number(int n)"},
    {"count_digits_in_base", "其他", "n 在 base 进制下的位数", "count_digits_in_base(int n, int base)"},
    {"is_semiprime", "其他", "是否为半素数(两素数之积)", "is_semiprime(int n)"},
    {"is_palindromic_prime", "其他", "是否为回文素数", "is_palindromic_prime(int n)"},
    {"is_binary_str", "其他", "字符串是否只含0/1", "is_binary_str(const char *s)"},
    {"is_octal_str", "其他", "字符串是否只含八进制字符", "is_octal_str(const char *s)"},
    {"is_decimal_str", "其他", "字符串是否为十进制数", "is_decimal_str(const char *s)"},
    {"is_hex_str", "其他", "字符串是否为十六进制数", "is_hex_str(const char *s)"},
    {"is_number_string", "其他", "字符串是否为数字(可带符号)", "is_number_string(const char *s)"},
    {"gcd_binary", "其他", "Stein 二进制最大公约数", "gcd_binary(int a, int b)"},
    {"prime_gap", "其他", "到下一个素数的间隔", "prime_gap(int n)"},
    {"count_trailing_zeros", "其他", "二进制末尾 0 的个数", "count_trailing_zeros(uint32_t n)"},
    {"is_power_of_three", "其他", "是否为 3 的幂", "is_power_of_three(int n)"},
    {"is_power_of_four", "其他", "是否为 4 的幂", "is_power_of_four(int n)"},
    {"digit_frequency", "其他", "数字 d 在 n 中出现次数", "digit_frequency(int n, int d)"},
    {"sum_abs_int", "其他", "绝对值之和", "sum_abs_int(int arr[], int size)"},
    {"dot_product_int", "其他", "两个数组点积", "dot_product_int(int a[], int b[], int size)"},
    {"longest_run_length", "其他", "最长连续相同段长度", "longest_run_length(int arr[], int size)"},
    {"find_local_max_idx", "其他", "局部极大值下标", "find_local_max_idx(int arr[], int size)"},
    {"find_local_min_idx", "其他", "局部极小值下标", "find_local_min_idx(int arr[], int size)"},
    {"equilibrium_index", "其他", "平衡点下标(左右和相等)", "equilibrium_index(int arr[], int size)"},
    {"reverse_subarray", "其他", "反转子数组 [lo,hi]", "reverse_subarray(int arr[], int size, int lo, int hi)"},
    {"swap_elements_int", "其他", "交换两个元素", "swap_elements_int(int arr[], int i, int j)"},
    {"fill_sequence_int", "其他", "填充递增序列 start..start+n-1", "fill_sequence_int(int arr[], int size, int start)"},
    {"fill_random_double_range", "其他", "填充随机浮点数范围", "fill_random_double_range(double arr[], int size, double min, double max)"},
    {"remove_all_value", "其他", "删除所有等于 value 的元素", "remove_all_value(int arr[], int *size, int value)"},
    {"count_distinct_int", "其他", "不同元素个数", "count_distinct_int(int arr[], int size)"},
    {"array_min_index", "其他", "最小值下标", "array_min_index(int arr[], int size)"},
    {"array_max_index", "其他", "最大值下标", "array_max_index(int arr[], int size)"},
    {"print_array_reverse_int", "其他", "倒序打印数组", "print_array_reverse_int(int arr[], int size)"},
    {"check_sorted_strict", "其他", "是否严格递增", "check_sorted_strict(int arr[], int size)"},
    {"min_gap", "其他", "相邻最小差值(需已排序)", "min_gap(int arr[], int size)"},
    {"max_gap", "其他", "相邻最大差值(需已排序)", "max_gap(int arr[], int size)"},
    {"list_get_nth", "其他", "取第 n 个节点的值", "list_get_nth(ListNode *head, int n, int *out)"},
    {"list_delete_nth", "其他", "删除第 n 个节点", "list_delete_nth(ListNode **head, int n)"},
    {"list_insert_nth", "其他", "在第 n 个位置插入", "list_insert_nth(ListNode **head, int n, int data)"},
    {"list_has_cycle", "其他", "检测链表是否有环(快慢指针)", "list_has_cycle(ListNode *head)"},
    {"list_middle_node", "其他", "链表中间节点", "list_middle_node(ListNode *head)"},
    {"list_from_array", "其他", "由数组构建链表", "list_from_array(int arr[], int size)"},
    {"list_max", "其他", "链表最大值", "list_max(ListNode *head)"},
    {"list_min", "其他", "链表最小值", "list_min(ListNode *head)"},
    {"list_sum", "其他", "链表元素之和", "list_sum(ListNode *head)"},
    {"list_sort", "其他", "链表排序(冒泡)", "list_sort(ListNode *head)"},
    {"list_merge_sorted", "其他", "合并两个升序链表", "list_merge_sorted(ListNode *a, ListNode *b)"},
    {"list_append_list", "其他", "把 b 接到 a 末尾(破坏性)", "list_append_list(ListNode *a, ListNode *b)"},
    {"list_clone", "其他", "深拷贝链表", "list_clone(ListNode *head)"},
    {"list_is_sorted", "其他", "链表是否升序", "list_is_sorted(ListNode *head)"},
    {"list_count_value", "其他", "统计值等于 value 的节点数", "list_count_value(ListNode *head, int value)"},
    {"list_rotate_right", "其他", "链表右旋 k 次", "list_rotate_right(ListNode **head, int k)"},
    {"int_to_binary_padded", "其他", "定宽二进制字符串(补0)", "int_to_binary_padded(int num, int width, char *buf, int buf_size)"},
    {"bcd_to_binary", "其他", "BCD 码转二进制", "bcd_to_binary(int bcd)"},
    {"binary_to_bcd", "其他", "二进制转 BCD 码", "binary_to_bcd(int n)"},
    {"float_bits_to_int", "其他", "浮点位模式转整数", "float_bits_to_int(float f)"},
    {"int_bits_to_float", "其他", "整数位模式转浮点", "int_bits_to_float(int i)"},
    {"double_to_hex_str", "其他", "浮点转十六进制字符串", "double_to_hex_str(double d, char *buf)"},
    {"char_to_ascii_code", "其他", "字符转 ASCII 码", "char_to_ascii_code(char c)"},
    {"ascii_code_to_char", "其他", "ASCII 码转字符", "ascii_code_to_char(int code)"},
    {"int_to_bytes_be", "其他", "整数转大端字节", "int_to_bytes_be(int val, uint8_t out[4])"},
    {"bytes_to_int_be", "其他", "大端字节转整数", "bytes_to_int_be(uint8_t b[4])"},
    {"int_to_hex_padded", "其他", "定宽十六进制字符串(补0)", "int_to_hex_padded(int num, int width, char *buf, int buf_size)"},
    {"triangle_area_coords", "其他", "三点坐标三角形面积", "triangle_area_coords(double x1, double y1, double x2, double y2, double x3, double y3)"},
    {"polygon_area", "其他", "多边形面积(鞋带公式)", "polygon_area(double x[], double y[], int n)"},
    {"distance_point_line", "其他", "点到直线距离", "distance_point_line(double px, double py, double ax, double ay, double bx, double by)"},
    {"distance_point_segment", "其他", "点到线段距离", "distance_point_segment(double px, double py, double ax, double ay, double bx, double by)"},
    {"area_sector", "其他", "扇形面积", "area_sector(double r, double angle_rad)"},
    {"arc_length", "其他", "弧长", "arc_length(double r, double angle_rad)"},
    {"sin_deg", "其他", "正弦(角度制)", "sin_deg(double deg)"},
    {"cos_deg", "其他", "余弦(角度制)", "cos_deg(double deg)"},
    {"tan_deg", "其他", "正切(角度制)", "tan_deg(double deg)"},
    {"angle_between_vectors", "其他", "两向量夹角(弧度)", "angle_between_vectors(double ax, double ay, double bx, double by)"},
    {"is_point_on_segment", "其他", "点是否在线段上", "is_point_on_segment(double px, double py, double ax, double ay, double bx, double by)"},
    {"is_positive_double", "其他", "是否为正数", "is_positive_double(double x)"},
    {"is_negative_double", "其他", "是否为负数", "is_negative_double(double x)"},
    {"is_zero_double", "其他", "是否为零", "is_zero_double(double x)"},
    {"step_function", "其他", "阶跃函数", "step_function(double x)"},
    {"round_to_n_decimals", "其他", "保留 n 位小数", "round_to_n_decimals(double x, int n)"},
    {"abs_diff_int", "其他", "整数绝对差", "abs_diff_int(int a, int b)"},
    {"abs_diff_double", "其他", "浮点绝对差", "abs_diff_double(double a, double b)"},
    {"max_double", "其他", "两数最大值", "max_double(double a, double b)"},
    {"min_double", "其他", "两数最小值", "min_double(double a, double b)"},
    {"reduce_fraction", "其他", "分数约分", "reduce_fraction(int num, int den, int *out_num, int *out_den)"},
    {"is_finite_double", "其他", "是否为有限浮点数", "is_finite_double(double x)"},
    {"is_nan_double", "其他", "是否为 NaN", "is_nan_double(double x)"},
    {"url_decode_str", "其他", "URL 解码(需free)", "url_decode_str(const char *s)"},
    {"html_escape_str", "其他", "HTML 转义(需free)", "html_escape_str(const char *s)"},
    {"bytes_to_hex_lower", "其他", "小写十六进制字符串", "bytes_to_hex_lower(const uint8_t *data, uint16_t len, char *buf, uint16_t buf_size)"},
    {"hex_str_to_upper", "其他", "十六进制字符串转大写", "hex_str_to_upper(const char *hex, char *buf, int buf_size)"},
    {"graph_is_connected", "其他", "图是否连通", "graph_is_connected(Graph *g)"},
    {"graph_edge_count", "其他", "无向边数量", "graph_edge_count(Graph *g)"},
    {"graph_transpose", "其他", "图的转置(out 需已分配 n x n)", "graph_transpose(Graph *g, int **out)"},
    {"graph_path_exists", "其他", "u 到 v 是否有路径(BFS)", "graph_path_exists(Graph *g, int u, int v)"},
    {"rand_range_excluding", "其他", "排除某个值的区间随机数", "rand_range_excluding(int min, int max, int excl)"},
    {"rand_fill_int_list", "其他", "填充随机整数列表", "rand_fill_int_list(int arr[], int size, int min, int max)"},
    {"rand_fill_float_array", "其他", "填充随机浮点数组", "rand_fill_float_array(double arr[], int size, double min, double max)"},
    {"rand_digit_char", "其他", "随机数字字符", "rand_digit_char(void)"},
    {"rand_lowercase_char", "其他", "随机小写字母", "rand_lowercase_char(void)"},
    {"rand_uppercase_char", "其他", "随机大写字母", "rand_uppercase_char(void)"},
    {"rand_letter_char", "其他", "随机字母(大小写)", "rand_letter_char(void)"},
    {"bst_min_value", "其他", "最小值", "bst_min_value(BSTNode *root)"},
    {"bst_max_value", "其他", "最大值", "bst_max_value(BSTNode *root)"},
    {"bst_count_leaves", "其他", "叶子节点数", "bst_count_leaves(BSTNode *root)"},
    {"bst_count_internal", "其他", "内部节点数", "bst_count_internal(BSTNode *root)"},
    {"bst_is_valid", "其他", "是否为合法 BST", "bst_is_valid(BSTNode *root)"},
    {"bst_is_balanced", "其他", "是否平衡(左右子树高差<=1)", "bst_is_balanced(BSTNode *root)"},
    {"bst_mirror", "其他", "镜像翻转(返回新根)", "bst_mirror(BSTNode *root)"},
    {"bst_same_tree", "其他", "两棵树是否相同", "bst_same_tree(BSTNode *a, BSTNode *b)"},
    {"bst_depth_of_value", "其他", "值为 value 的节点深度(根为0)", "bst_depth_of_value(BSTNode *root, int value)"},
    {"mat_zeros", "其他", "创建全零矩阵", "mat_zeros(int rows, int cols)"},
    {"mat_ones", "其他", "创建全一矩阵", "mat_ones(int rows, int cols)"},
    {"mat_identity_alloc", "其他", "创建单位矩阵", "mat_identity_alloc(int n)"},
    {"mat_transpose_alloc", "其他", "转置并返回新矩阵", "mat_transpose_alloc(double **m, int rows, int cols)"},
    {"mat_is_symmetric", "其他", "是否对称矩阵", "mat_is_symmetric(double **m, int n)"},
    {"mat_add_scalar", "其他", "矩阵加标量", "mat_add_scalar(double **m, int rows, int cols, double s, double **out)"},
    {"mat_negate", "其他", "矩阵取负", "mat_negate(double **m, int rows, int cols, double **out)"},
    {"mat_avg", "其他", "矩阵元素平均值", "mat_avg(double **m, int rows, int cols)"},
    {"mat_rand_fill", "其他", "随机填充矩阵", "mat_rand_fill(double **m, int rows, int cols, double min, double max)"},
    {"mode_double_array", "其他", "众数(double数组)", "mode_double_array(double arr[], int size)"},
    {"median_int_array", "其他", "中位数(int数组)", "median_int_array(int arr[], int size)"},
    {"variance_int_array", "其他", "方差(int数组)", "variance_int_array(int arr[], int size)"},
    {"stddev_int_array", "其他", "标准差(int数组)", "stddev_int_array(int arr[], int size)"},
    {"range_int_array", "其他", "极差(int数组)", "range_int_array(int arr[], int size)"},
    {"int_array_min_index", "其他", "最小值下标", "int_array_min_index(int arr[], int size)"},
    {"int_array_max_index", "其他", "最大值下标", "int_array_max_index(int arr[], int size)"},
    {"int_array_count_greater", "其他", "统计大于 value 的元素个数", "int_array_count_greater(int arr[], int size, int value)"},
    {"int_array_count_less", "其他", "统计小于 value 的元素个数", "int_array_count_less(int arr[], int size, int value)"},
    {"int_array_scale", "其他", "每个元素乘以 scalar", "int_array_scale(int arr[], int size, int scalar)"},
    {"int_array_add_scalar", "其他", "每个元素加 offset", "int_array_add_scalar(int arr[], int size, int offset)"},
    {"int_array_has_duplicates", "其他", "数组是否有重复", "int_array_has_duplicates(int arr[], int size)"},
    {"int_array_rotate_left", "其他", "数组左旋 k 位", "int_array_rotate_left(int arr[], int size, int k)"},
    {"int_array_sum_abs", "其他", "绝对值之和", "int_array_sum_abs(int arr[], int size)"},
    {"long_array_min_index", "其他", "最小值下标", "long_array_min_index(long arr[], int size)"},
    {"long_array_max_index", "其他", "最大值下标", "long_array_max_index(long arr[], int size)"},
    {"long_array_count_greater", "其他", "统计大于 value 的元素个数", "long_array_count_greater(long arr[], int size, long value)"},
    {"long_array_count_less", "其他", "统计小于 value 的元素个数", "long_array_count_less(long arr[], int size, long value)"},
    {"long_array_scale", "其他", "每个元素乘以 scalar", "long_array_scale(long arr[], int size, long scalar)"},
    {"long_array_add_scalar", "其他", "每个元素加 offset", "long_array_add_scalar(long arr[], int size, long offset)"},
    {"long_array_has_duplicates", "其他", "数组是否有重复", "long_array_has_duplicates(long arr[], int size)"},
    {"long_array_rotate_left", "其他", "数组左旋 k 位", "long_array_rotate_left(long arr[], int size, int k)"},
    {"long_array_sum_abs", "其他", "绝对值之和", "long_array_sum_abs(long arr[], int size)"},
    {"long_long_array_min_index", "其他", "最小值下标", "long_long_array_min_index(long long arr[], int size)"},
    {"long_long_array_max_index", "其他", "最大值下标", "long_long_array_max_index(long long arr[], int size)"},
    {"long_long_array_count_greater", "其他", "统计大于 value 的元素个数", "long_long_array_count_greater(long long arr[], int size, long long value)"},
    {"long_long_array_count_less", "其他", "统计小于 value 的元素个数", "long_long_array_count_less(long long arr[], int size, long long value)"},
    {"long_long_array_scale", "其他", "每个元素乘以 scalar", "long_long_array_scale(long long arr[], int size, long long scalar)"},
    {"long_long_array_add_scalar", "其他", "每个元素加 offset", "long_long_array_add_scalar(long long arr[], int size, long long offset)"},
    {"long_long_array_has_duplicates", "其他", "数组是否有重复", "long_long_array_has_duplicates(long long arr[], int size)"},
    {"long_long_array_rotate_left", "其他", "数组左旋 k 位", "long_long_array_rotate_left(long long arr[], int size, int k)"},
    {"long_long_array_sum_abs", "其他", "绝对值之和", "long_long_array_sum_abs(long long arr[], int size)"},
    {"short_array_min_index", "其他", "最小值下标", "short_array_min_index(short arr[], int size)"},
    {"short_array_max_index", "其他", "最大值下标", "short_array_max_index(short arr[], int size)"},
    {"short_array_count_greater", "其他", "统计大于 value 的元素个数", "short_array_count_greater(short arr[], int size, short value)"},
    {"short_array_count_less", "其他", "统计小于 value 的元素个数", "short_array_count_less(short arr[], int size, short value)"},
    {"short_array_scale", "其他", "每个元素乘以 scalar", "short_array_scale(short arr[], int size, short scalar)"},
    {"short_array_add_scalar", "其他", "每个元素加 offset", "short_array_add_scalar(short arr[], int size, short offset)"},
    {"short_array_has_duplicates", "其他", "数组是否有重复", "short_array_has_duplicates(short arr[], int size)"},
    {"short_array_rotate_left", "其他", "数组左旋 k 位", "short_array_rotate_left(short arr[], int size, int k)"},
    {"short_array_sum_abs", "其他", "绝对值之和", "short_array_sum_abs(short arr[], int size)"},
    {"uint_array_min_index", "其他", "最小值下标", "uint_array_min_index(unsigned int arr[], int size)"},
    {"uint_array_max_index", "其他", "最大值下标", "uint_array_max_index(unsigned int arr[], int size)"},
    {"uint_array_count_greater", "其他", "统计大于 value 的元素个数", "uint_array_count_greater(unsigned int arr[], int size, unsigned int value)"},
    {"uint_array_count_less", "其他", "统计小于 value 的元素个数", "uint_array_count_less(unsigned int arr[], int size, unsigned int value)"},
    {"uint_array_scale", "其他", "每个元素乘以 scalar", "uint_array_scale(unsigned int arr[], int size, unsigned int scalar)"},
    {"uint_array_add_scalar", "其他", "每个元素加 offset", "uint_array_add_scalar(unsigned int arr[], int size, unsigned int offset)"},
    {"uint_array_has_duplicates", "其他", "数组是否有重复", "uint_array_has_duplicates(unsigned int arr[], int size)"},
    {"uint_array_rotate_left", "其他", "数组左旋 k 位", "uint_array_rotate_left(unsigned int arr[], int size, int k)"},
    {"float_array_min_index", "其他", "最小值下标", "float_array_min_index(float arr[], int size)"},
    {"float_array_max_index", "其他", "最大值下标", "float_array_max_index(float arr[], int size)"},
    {"float_array_count_greater", "其他", "统计大于 value 的元素个数", "float_array_count_greater(float arr[], int size, float value)"},
    {"float_array_count_less", "其他", "统计小于 value 的元素个数", "float_array_count_less(float arr[], int size, float value)"},
    {"float_array_scale", "其他", "每个元素乘以 scalar", "float_array_scale(float arr[], int size, float scalar)"},
    {"float_array_add_scalar", "其他", "每个元素加 offset", "float_array_add_scalar(float arr[], int size, float offset)"},
    {"float_array_has_duplicates", "其他", "数组是否有重复", "float_array_has_duplicates(float arr[], int size)"},
    {"float_array_rotate_left", "其他", "数组左旋 k 位", "float_array_rotate_left(float arr[], int size, int k)"},
    {"float_array_sum_abs", "其他", "绝对值之和", "float_array_sum_abs(float arr[], int size)"},
    {"double_array_min_index", "其他", "最小值下标", "double_array_min_index(double arr[], int size)"},
    {"double_array_max_index", "其他", "最大值下标", "double_array_max_index(double arr[], int size)"},
    {"double_array_count_greater", "其他", "统计大于 value 的元素个数", "double_array_count_greater(double arr[], int size, double value)"},
    {"double_array_count_less", "其他", "统计小于 value 的元素个数", "double_array_count_less(double arr[], int size, double value)"},
    {"double_array_scale", "其他", "每个元素乘以 scalar", "double_array_scale(double arr[], int size, double scalar)"},
    {"double_array_add_scalar", "其他", "每个元素加 offset", "double_array_add_scalar(double arr[], int size, double offset)"},
    {"double_array_has_duplicates", "其他", "数组是否有重复", "double_array_has_duplicates(double arr[], int size)"},
    {"double_array_rotate_left", "其他", "数组左旋 k 位", "double_array_rotate_left(double arr[], int size, int k)"},
    {"double_array_sum_abs", "其他", "绝对值之和", "double_array_sum_abs(double arr[], int size)"},
    {"char_array_min_index", "其他", "最小值下标", "char_array_min_index(char arr[], int size)"},
    {"char_array_max_index", "其他", "最大值下标", "char_array_max_index(char arr[], int size)"},
    {"char_array_count_greater", "其他", "统计大于 value 的元素个数", "char_array_count_greater(char arr[], int size, char value)"},
    {"char_array_count_less", "其他", "统计小于 value 的元素个数", "char_array_count_less(char arr[], int size, char value)"},
    {"char_array_scale", "其他", "每个元素乘以 scalar", "char_array_scale(char arr[], int size, char scalar)"},
    {"char_array_add_scalar", "其他", "每个元素加 offset", "char_array_add_scalar(char arr[], int size, char offset)"},
    {"char_array_has_duplicates", "其他", "数组是否有重复", "char_array_has_duplicates(char arr[], int size)"},
    {"char_array_rotate_left", "其他", "数组左旋 k 位", "char_array_rotate_left(char arr[], int size, int k)"},
    {"char_array_sum_abs", "其他", "绝对值之和", "char_array_sum_abs(char arr[], int size)"},
    {"uint8_array_min_index", "其他", "最小值下标", "uint8_array_min_index(uint8_t arr[], int size)"},
    {"uint8_array_max_index", "其他", "最大值下标", "uint8_array_max_index(uint8_t arr[], int size)"},
    {"uint8_array_count_greater", "其他", "统计大于 value 的元素个数", "uint8_array_count_greater(uint8_t arr[], int size, uint8_t value)"},
    {"uint8_array_count_less", "其他", "统计小于 value 的元素个数", "uint8_array_count_less(uint8_t arr[], int size, uint8_t value)"},
    {"uint8_array_scale", "其他", "每个元素乘以 scalar", "uint8_array_scale(uint8_t arr[], int size, uint8_t scalar)"},
    {"uint8_array_add_scalar", "其他", "每个元素加 offset", "uint8_array_add_scalar(uint8_t arr[], int size, uint8_t offset)"},
    {"uint8_array_has_duplicates", "其他", "数组是否有重复", "uint8_array_has_duplicates(uint8_t arr[], int size)"},
    {"uint8_array_rotate_left", "其他", "数组左旋 k 位", "uint8_array_rotate_left(uint8_t arr[], int size, int k)"},
    {"uint16_array_min_index", "其他", "最小值下标", "uint16_array_min_index(uint16_t arr[], int size)"},
    {"uint16_array_max_index", "其他", "最大值下标", "uint16_array_max_index(uint16_t arr[], int size)"},
    {"uint16_array_count_greater", "其他", "统计大于 value 的元素个数", "uint16_array_count_greater(uint16_t arr[], int size, uint16_t value)"},
    {"uint16_array_count_less", "其他", "统计小于 value 的元素个数", "uint16_array_count_less(uint16_t arr[], int size, uint16_t value)"},
    {"uint16_array_scale", "其他", "每个元素乘以 scalar", "uint16_array_scale(uint16_t arr[], int size, uint16_t scalar)"},
    {"uint16_array_add_scalar", "其他", "每个元素加 offset", "uint16_array_add_scalar(uint16_t arr[], int size, uint16_t offset)"},
    {"uint16_array_has_duplicates", "其他", "数组是否有重复", "uint16_array_has_duplicates(uint16_t arr[], int size)"},
    {"uint16_array_rotate_left", "其他", "数组左旋 k 位", "uint16_array_rotate_left(uint16_t arr[], int size, int k)"},
    {"uint32_array_min_index", "其他", "最小值下标", "uint32_array_min_index(uint32_t arr[], int size)"},
    {"uint32_array_max_index", "其他", "最大值下标", "uint32_array_max_index(uint32_t arr[], int size)"},
    {"uint32_array_count_greater", "其他", "统计大于 value 的元素个数", "uint32_array_count_greater(uint32_t arr[], int size, uint32_t value)"},
    {"uint32_array_count_less", "其他", "统计小于 value 的元素个数", "uint32_array_count_less(uint32_t arr[], int size, uint32_t value)"},
    {"uint32_array_scale", "其他", "每个元素乘以 scalar", "uint32_array_scale(uint32_t arr[], int size, uint32_t scalar)"},
    {"uint32_array_add_scalar", "其他", "每个元素加 offset", "uint32_array_add_scalar(uint32_t arr[], int size, uint32_t offset)"},
    {"uint32_array_has_duplicates", "其他", "数组是否有重复", "uint32_array_has_duplicates(uint32_t arr[], int size)"},
    {"uint32_array_rotate_left", "其他", "数组左旋 k 位", "uint32_array_rotate_left(uint32_t arr[], int size, int k)"},
    {"count_runs_int", "其他", "连续相同段的数量", "count_runs_int(int arr[], int size)"},
    {"is_permutation_int", "其他", "是否为 1..n 的排列", "is_permutation_int(int arr[], int size)"},
    {"max_pair_product", "其他", "任意两数最大乘积", "max_pair_product(int arr[], int size)"},
    {"find_missing_number", "其他", "找缺失数字(0..n 缺一个)", "find_missing_number(int arr[], int n)"},
    {"find_duplicate_number", "其他", "找重复数字(1..n 有一个重复)", "find_duplicate_number(int arr[], int n)"},
    {"move_zeros_to_end", "其他", "把 0 移到末尾", "move_zeros_to_end(int arr[], int size)"},
    {"move_negatives_to_front", "其他", "把负数移到前面", "move_negatives_to_front(int arr[], int size)"},
    {"separate_even_odd", "其他", "奇偶分离(偶数在前)", "separate_even_odd(int arr[], int size)"},
    {"sum_range_int", "其他", "区间和(直接计算)", "sum_range_int(int arr[], int lo, int hi)"},
    {"count_occurrences_sorted", "其他", "排序数组中 target 出现次数", "count_occurrences_sorted(int arr[], int size, int target)"},
    {"reverse_in_groups", "其他", "按 k 分组反转", "reverse_in_groups(int arr[], int size, int k)"},
    {"is_mountain_array", "其他", "是否为山脉数组", "is_mountain_array(int arr[], int size)"},
    {"majority_element", "其他", "多数元素(Boyer-Moore)", "majority_element(int arr[], int size)"},
    {"pairs_with_sum", "其他", "和为 target 的数对数量", "pairs_with_sum(int arr[], int size, int target)"},
    {"next_greater_element", "其他", "单调递增栈(写入结果数组)", "next_greater_element(int arr[], int size, int out[])"},
    {"find_peak_index", "其他", "山峰下标(严格单峰)", "find_peak_index(int arr[], int size)"},
    {"str_rot13_copy", "其他", "ROT13 副本(需free)", "str_rot13_copy(const char *s)"},
    {"str_caesar_copy", "其他", "凯撒加密副本(需free)", "str_caesar_copy(const char *s, int shift)"},
    {"str_replace_all", "其他", "替换所有子串(需free)", "str_replace_all(const char *s, const char *old, const char *new)"},
    {"str_extract_digits", "其他", "提取数字(需free)", "str_extract_digits(const char *s)"},
    {"str_remove_char_at", "其他", "删除指定位置字符", "str_remove_char_at(char *str, int pos)"},
    {"str_insert_char_at", "其他", "在指定位置插入字符", "str_insert_char_at(char *str, int buf_size, int pos, char c)"},
    {"str_is_all_same_char", "其他", "是否所有字符相同", "str_is_all_same_char(const char *str)"},
    {"str_has_duplicate_chars", "其他", "是否有重复字符", "str_has_duplicate_chars(const char *str)"},
    {"str_longest_common_prefix", "其他", "两字符串最长公共前缀长度", "str_longest_common_prefix(const char *a, const char *b)"},
    {"str_count_unique_chars", "其他", "不同字符个数", "str_count_unique_chars(const char *str)"},
    {"str_last_word_len", "其他", "最后一个单词长度", "str_last_word_len(const char *str)"},
    {"str_first_word_len", "其他", "第一个单词长度", "str_first_word_len(const char *str)"},
    {"str_contains_any_char", "其他", "是否包含任意给定字符", "str_contains_any_char(const char *str, const char *chars)"},
    {"str_is_balanced_parens", "其他", "括号是否匹配", "str_is_balanced_parens(const char *str)"},
    {"str_is_valid_brackets", "其他", "括号组是否合法({[]})", "str_is_valid_brackets(const char *s)"},
    {"str_similarity", "其他", "字符串相似度(简单字符重合率0~100)", "str_similarity(const char *a, const char *b)"},
    {"gcd_of_array", "其他", "数组的最大公约数", "gcd_of_array(int arr[], int size)"},
    {"lcm_of_array", "其他", "数组的最小公倍数", "lcm_of_array(int arr[], int size)"},
    {"sum_of_squares_digits", "其他", "各位数字平方和", "sum_of_squares_digits(int n)"},
    {"is_pandigital", "其他", "是否全数字数(1..len各一次)", "is_pandigital(int n)"},
    {"is_repdigit", "其他", "是否重位数(各位相同)", "is_repdigit(int n)"},
    {"digit_product", "其他", "各位数字之积", "digit_product(int n)"},
    {"nth_triangular", "其他", "第 n 个三角形数", "nth_triangular(int n)"},
    {"fib_sum_first", "其他", "前 n 个斐波那契和", "fib_sum_first(int n)"},
    {"is_ugly_number", "其他", "是否丑数(因子只有2,3,5)", "is_ugly_number(int n)"},
    {"is_square_free", "其他", "是否无平方因子数", "is_square_free(int n)"},
    {"radical", "其他", "无平方因子积(radical)", "radical(int n)"},
    {"is_emirp", "其他", "是否反素数(逆转仍是素数)", "is_emirp(int n)"},
    {"count_coprimes", "其他", "1..n 中与 n 互质的个数", "count_coprimes(int n)"},
    {"int_to_gray", "其他", "十进制转格雷码", "int_to_gray(uint32_t n)"},
    {"gray_to_int", "其他", "格雷码转十进制", "gray_to_int(uint32_t g)"},
    {"clamp_long", "其他", "长整数裁剪", "clamp_long(long v, long lo, long hi)"},
    {"clamp_float", "其他", "单精度裁剪", "clamp_float(float v, float lo, float hi)"},
    {"lerp_clamped", "其他", "限制线性插值", "lerp_clamped(double a, double b, double t)"},
    {"smoothstep", "其他", "Smoothstep 平滑插值", "smoothstep(double x)"},
    {"normalize_01", "其他", "归一化到 [0,1]", "normalize_01(double x, double min, double max)"},
    {"int_divide_ceil", "其他", "整数向上整除", "int_divide_ceil(long long a, long long b)"},
    {"int_divide_floor", "其他", "整数向下整除", "int_divide_floor(long long a, long long b)"},
    {"is_between_int", "其他", "是否在区间内(含端点)", "is_between_int(int v, int lo, int hi)"},
    {"is_between_double", "其他", "是否在区间内(浮点)", "is_between_double(double v, double lo, double hi)"},
    {"percent_delta", "其他", "百分比变化", "percent_delta(double a, double b)"},
    {"average_of_three", "其他", "三个数平均值", "average_of_three(double a, double b, double c)"},
    {"product_of_three", "其他", "三个数乘积", "product_of_three(double a, double b, double c)"},
    {"sign_double", "其他", "浮点符号(1/-1/0)", "sign_double(double x)"},
    {"percent_of", "其他", "百分比保留", "percent_of(double part, double total)"},
    {"distance_1d", "其他", "两点在数轴上的距离", "distance_1d(double a, double b)"},
    {"clear_high_bits", "其他", "保留低 n 位", "clear_high_bits(uint32_t val, int n)"},
    {"toggle_bits", "其他", "按掩码翻转位", "toggle_bits(uint32_t val, uint32_t mask)"},
    {"set_bits_mask", "其他", "按掩码置位", "set_bits_mask(uint32_t val, uint32_t mask)"},
    {"clear_bits_mask", "其他", "按掩码清位", "clear_bits_mask(uint32_t val, uint32_t mask)"},
    {"bit_reverse_byte", "其他", "反转单个字节", "bit_reverse_byte(uint8_t b)"},
    {"int_to_gray16", "其他", "16 位格雷码转换", "int_to_gray16(uint16_t n)"},
    {"is_single_bit", "其他", "判断是否只有一个 1", "is_single_bit(uint32_t val)"},
    {"lowest_one", "其他", "最低位 1 的值", "lowest_one(uint32_t val)"},
    {"byte_to_bin_str", "其他", "字节转 8 位二进制字符串", "byte_to_bin_str(uint8_t b, char *buf, int buf_size)"},
    {"word_to_bin_str", "其他", "16 位转二进制字符串", "word_to_bin_str(uint16_t w, char *buf, int buf_size)"},
    {"float_to_int_round", "其他", "浮点转整数(四舍五入)", "float_to_int_round(float f)"},
    {"float_to_int_truncate", "其他", "浮点转整数(截断)", "float_to_int_truncate(float f)"},
    {"long_to_str", "其他", "整数转 long 字符串", "long_to_str(long v, char *buf)"},
    {"char_array_to_long", "其他", "字符数组转长整数(限长)", "char_array_to_long(const char *s, int len)"},
    {"dec_str_to_hex_str", "其他", "十进制字符串直接转十六进制字符串", "dec_str_to_hex_str(const char *dec, char *buf, int buf_size)"},
    {"print_progress_bar", "其他", "打印进度条", "print_progress_bar(int percent, int width)"},
    {"print_ok", "其他", "打印带颜色的成功信息", "print_ok(const char *msg)"},
    {"print_fail", "其他", "打印带颜色的失败信息", "print_fail(const char *msg)"},
    {"print_warn", "其他", "打印带颜色的警告信息", "print_warn(const char *msg)"},
    {"log_timestamp", "其他", "带时间戳打印普通日志", "log_timestamp(const char *msg)"},
    {"print_padded_int", "其他", "定宽打印整数", "print_padded_int(int v, int width)"},
    {"print_bool", "其他", "打印布尔值", "print_bool(int b)"},
    {"print_center", "其他", "居中打印标题", "print_center(const char *title, int width)"},
    {"fibonacci_array", "其他", "填充前 n 个斐波那契数", "fibonacci_array(long long out[], int n)"},
    {"square_array", "其他", "填充前 n 个平方数", "square_array(long long out[], int n)"},
    {"triangular_array", "其他", "填充前 n 个三角形数", "triangular_array(long long out[], int n)"},
    {"collatz_sequence", "其他", "填充科拉茨序列", "collatz_sequence(int n, int out[], int max_len)"},
    {"pascal_row", "其他", "杨辉三角第 n 行", "pascal_row(int n, int out[], int *len)"},
    {"is_arithmetic_sequence", "其他", "是否等差数列", "is_arithmetic_sequence(int arr[], int size)"},
    {"is_geometric_sequence", "其他", "是否等比数列", "is_geometric_sequence(double arr[], int size)"},
    {"subfactorial", "其他", "错排数(子阶乘)", "subfactorial(int n)"},
    {"lucas_number", "其他", "第 n 个卢卡斯数", "lucas_number(int n)"},
    {"file_clear", "其他", "清空文件内容", "file_clear(const char *filename)"},
    {"file_read_all_bytes", "其他", "读取整个文件为字节(需free)", "file_read_all_bytes(const char *filename, size_t *out_len)"},
    {"file_write_bytes", "其他", "写入字节到文件", "file_write_bytes(const char *filename, const uint8_t *data, size_t len)"},
    {"file_count_words", "其他", "统计文件中的单词数", "file_count_words(const char *filename)"},
    {"file_has_line", "其他", "文件是否包含指定行", "file_has_line(const char *filename, const char *line)"},
    {"sort_asc", "其他", "升序排序(包装冒泡)", "sort_asc(int arr[], int size)"},
    {"sort_desc", "其他", "降序排序", "sort_desc(int arr[], int size)"},
    {"sort_double_asc", "其他", "double 数组升序(冒泡)", "sort_double_asc(double arr[], int size)"},
    {"sort_float_asc", "其他", "float 数组升序(冒泡)", "sort_float_asc(float arr[], int size)"},
    {"sort_long_asc", "其他", "long 数组升序(冒泡)", "sort_long_asc(long arr[], int size)"},
    {"sort_char_asc", "其他", "char 数组升序(冒泡)", "sort_char_asc(char arr[], int size)"},
    {"sort_unique", "其他", "排序并去重(返回新长度)", "sort_unique(int arr[], int *size)"},
    {"sort_indices", "其他", "排序索引(返回索引数组需free)", "sort_indices(int arr[], int size)"},
    {"interpolation_search", "其他", "插值查找(升序)", "interpolation_search(int arr[], int size, int target)"},
    {"sentinel_search", "其他", "哨兵查找", "sentinel_search(int arr[], int size, int target)"},
    {"fibonacci_search", "其他", "斐波那契查找(升序)", "fibonacci_search(int arr[], int size, int target)"},
    {"kmp_search", "其他", "KMP 字符串匹配", "kmp_search(const char *text, const char *pattern)"},
    {"str_longest_common_substr", "其他", "最长公共子串长度", "str_longest_common_substr(const char *s1, const char *s2)"},
    {"str_edit_distance", "其他", "编辑距离(莱文斯坦)", "str_edit_distance(const char *s1, const char *s2)"},
    {"str_reverse_words", "其他", "反转句子单词顺序", "str_reverse_words(char *str)"},
    {"build_prefix_sum", "其他", "构建前缀和数组(需free)", "build_prefix_sum(int arr[], int size)"},
    {"range_sum_query", "其他", "前缀和区间查询", "range_sum_query(long long pre[], int l, int r)"},
    {"build_diff_array", "其他", "构建差分数组", "build_diff_array(int arr[], int size, int diff[])"},
    {"apply_diff_array", "其他", "差分数组还原", "apply_diff_array(int diff[], int size, int out[])"},
    {"sieve_primes", "其他", "埃氏筛求素数(需free)", "sieve_primes(int n, int *count)"},
    {"prime_factors", "其他", "质因数分解", "prime_factors(int n, int factors[], int *count)"},
    {"mod_pow", "其他", "快速幂取模", "mod_pow(long long base, long long exp, long long mod)"},
    {"extended_gcd", "其他", "扩展欧几里得", "extended_gcd(int a, int b, int *x, int *y)"},
    {"next_permutation", "其他", "下一个字典序排列", "next_permutation(int arr[], int size)"},
    {"is_leap_year", "其他", "闰年判断", "is_leap_year(int year)"},
    {"is_power_of_two", "其他", "判断 2 的幂", "is_power_of_two(int n)"},
    {"lowest_set_bit", "其他", "最低位 1 的位置", "lowest_set_bit(uint32_t n)"},
    {"find_single_number", "其他", "异或找唯一出现一次的数", "find_single_number(int arr[], int size)"},
    {"hamming_distance", "其他", "汉明距离", "hamming_distance(uint32_t a, uint32_t b)"},
    {"knapsack01", "其他", "0-1 背包最大价值", "knapsack01(int weights[], int values[], int n, int capacity)"},
    {"lis_length", "其他", "最长递增子序列长度", "lis_length(int arr[], int size)"},
    {"djb2_hash", "其他", "DJB2 哈希", "djb2_hash(const char *str)"},
    {"fnv1a_hash", "其他", "FNV-1a 哈希", "fnv1a_hash(const char *str)"},
    {"sdbm_hash", "其他", "SDBM 哈希", "sdbm_hash(const char *str)"},
    {"bkdr_hash", "其他", "BKDR 哈希", "bkdr_hash(const char *str)"},
    {"rb_create", "其他", "创建环形缓冲区", "rb_create(uint16_t capacity)"},
    {"rb_destroy", "其他", "销毁环形缓冲区", "rb_destroy(RingBuffer *rb)"},
    {"rb_write", "其他", "写入一个字节", "rb_write(RingBuffer *rb, uint8_t byte)"},
    {"rb_read", "其他", "读取一个字节", "rb_read(RingBuffer *rb, uint8_t *out)"},
    {"rb_peek", "其他", "查看队首字节", "rb_peek(RingBuffer *rb, uint8_t *out)"},
    {"rb_available", "其他", "可读字节数", "rb_available(RingBuffer *rb)"},
    {"rb_free", "其他", "剩余空间", "rb_free(RingBuffer *rb)"},
    {"rb_is_empty", "其他", "是否为空", "rb_is_empty(RingBuffer *rb)"},
    {"rb_is_full", "其他", "是否为满", "rb_is_full(RingBuffer *rb)"},
    {"rb_clear", "其他", "清空缓冲区", "rb_clear(RingBuffer *rb)"},
    {"vec_create", "其他", "创建动态数组", "vec_create(int init_capacity)"},
    {"vec_destroy", "其他", "销毁动态数组", "vec_destroy(Vector *v)"},
    {"vec_push_back", "其他", "尾部追加", "vec_push_back(Vector *v, int value)"},
    {"vec_pop_back", "其他", "尾部弹出", "vec_pop_back(Vector *v, int *out)"},
    {"vec_get", "其他", "按下标取值", "vec_get(Vector *v, int index, int *out)"},
    {"vec_set", "其他", "按下标赋值", "vec_set(Vector *v, int index, int value)"},
    {"vec_size", "其他", "元素个数", "vec_size(Vector *v)"},
    {"vec_capacity", "其他", "当前容量", "vec_capacity(Vector *v)"},
    {"vec_is_empty", "其他", "是否为空", "vec_is_empty(Vector *v)"},
    {"vec_clear", "其他", "清空(不释放)", "vec_clear(Vector *v)"},
    {"vec_insert", "其他", "按下标插入", "vec_insert(Vector *v, int index, int value)"},
    {"vec_remove", "其他", "按下标删除", "vec_remove(Vector *v, int index, int *out)"},
    {"pq_create", "其他", "创建最大堆队列", "pq_create(int capacity)"},
    {"pq_destroy", "其他", "销毁队列", "pq_destroy(PriorityQueue *pq)"},
    {"pq_push", "其他", "入队", "pq_push(PriorityQueue *pq, int value)"},
    {"pq_pop", "其他", "弹出最大值", "pq_pop(PriorityQueue *pq, int *out)"},
    {"pq_peek", "其他", "查看最大值", "pq_peek(PriorityQueue *pq, int *out)"},
    {"pq_is_empty", "其他", "是否为空", "pq_is_empty(PriorityQueue *pq)"},
    {"pq_size", "其他", "元素个数", "pq_size(PriorityQueue *pq)"},
    {"bst_insert", "其他", "BST 插入节点", "bst_insert(BSTNode *root, int data)"},
    {"bst_search", "其他", "BST 查找节点", "bst_search(BSTNode *root, int data)"},
    {"bst_find_min", "其他", "BST 最小节点", "bst_find_min(BSTNode *root)"},
    {"bst_find_max", "其他", "BST 最大节点", "bst_find_max(BSTNode *root)"},
    {"bst_delete", "其他", "BST 删除节点", "bst_delete(BSTNode *root, int data)"},
    {"bst_height", "其他", "BST 树高", "bst_height(BSTNode *root)"},
    {"bst_node_count", "其他", "BST 节点数", "bst_node_count(BSTNode *root)"},
    {"bst_inorder", "其他", "BST 中序遍历", "bst_inorder(BSTNode *root)"},
    {"bst_preorder", "其他", "BST 前序遍历", "bst_preorder(BSTNode *root)"},
    {"bst_postorder", "其他", "BST 后序遍历", "bst_postorder(BSTNode *root)"},
    {"bst_levelorder", "其他", "BST 层序遍历", "bst_levelorder(BSTNode *root)"},
    {"bst_free", "其他", "BST 释放整棵树", "bst_free(BSTNode *root)"},
    {"get_timestamp_ms", "其他", "毫秒级时间戳", "get_timestamp_ms(void)"},
    {"get_timestamp_us", "其他", "微秒级时间戳", "get_timestamp_us(void)"},
    {"log_to_file", "其他", "带时间戳写入日志文件", "log_to_file(const char *filename, const char *format, ...)"},
};

#define FUNC_COUNT ((int)(sizeof(g_funcs) / sizeof(g_funcs[0])))

#endif /* FUNC_INDEX_H */
